export const EPIC_IMAGES: Record<string, any> = {
    alger_wilson: require('./alger_wilson.png'),
    alice_zuberg: require('./alice_zuberg.png'),
    eileen_the_crow: require('./eileen_the_crow.png'),
    endeavor: require('./endeavor.png'),
    eugeo: require('./eugeo.png'),
    father_gascoigne: require('./father_gascoigne.png'),
    genos: require('./genos.png'),
    hawks: require('./hawks.png'),
    heathcliff_kayaba: require('./heathcliff_kayaba.png'),
    impa: require('./impa.png'),
    izuku_midoriya: require('./izuku_midoriya.png'),
    katsuki_bakugo: require('./katsuki_bakugo.png'),
    link: require('./link.png'),
    megumi_fushiguro: require('./megumi_fushiguro.png'),
    nanami_kento: require('./nanami_kento.png'),
    nyanta: require('./nyanta.png'),
    petelgeuse: require('./petelgeuse.png'),
    roswaal: require('./roswaal.png'),
    shoto_todoroki: require('./shoto_todoroki.png'),
    suguru_geto: require('./suguru_geto.png'),
    tomura_shigaraki: require('./tomura_shigaraki.png'),
    touka_kirishima: require('./touka_kirishima.png'),
    yuji_itadori: require('./yuji_itadori.png'),
    yuta_okkotsu: require('./yuta_okkotsu.png'),
};
