export const LEGENDARY_IMAGES: Record<string, any> = {
    cell: require('./cell.png'),
    frieza: require('./frieza.png'),
    giyu_tomioka: require('./giyu_tomioka.png'),
    gohan: require('./gohan.png'),
    grimmjow_jaegerjaquez: require('./grimmjow_jaegerjaquez.png'),
    jinbe: require('./jinbe.png'),
    kaguya_otsutsuki: require('./kaguya_otsutsuki.png'),
    levi_ackerman: require('./levi_ackerman.png'),
    meruem: require('./meruem.png'),
    might_guy: require('./might_guy.gif'),
    piccolo: require('./piccolo.png'),
    reiner_braun: require('./reiner_braun.png'),
    sabo: require('./sabo.png'),
    sanji: require('./sanji.gif'),
    sasuke_uchiha: require('./sasuke_uchiha.gif'),
    tengen_uzui: require('./tengen_uzui.png'),
    tomura_shigaraki: require('./tomura_shigaraki.png'),
    trunks: require('./trunks.png'),
    vegeta: require('./vegeta.png'),
    zeke_yeager: require('./zeke_yeager.png'),
};

/** فيديوهات الكروت الأسطورية — mp4 */
export const LEGENDARY_VIDEOS: Record<string, any> = {
    akaza: require('./akaza.mp4'),
    all_might: require('./all_might.mp4'),
    broly: require('./broly.mp4'),
    byakuya_kuchiki: require('./byakuya_kuchiki.mp4'),
    chrollo_lucilfer: require('./chrollo_lucilfer.mp4'),
    doma: require('./doma.mp4'),
    endeavor: require('./endeavor.mp4'),
    eren_yeager: require('./eren_yeager.mp4'),
    gehrman: require('./gehrman.mp4'),
    ichigo_kurosaki: require('./ichigo_kurosaki.mp4'),
    itachi_uchiha: require('./itachi_uchiha.mp4'),
    jiraiya: require('./jiraiya.mp4'),
    kaido: require('./kaido.mp4'),
    madara_uchiha: require('./madara_uchiha.mp4'),
    minato_namikaze: require('./minato_namikaze.mp4'),
    naruto_uzumaki: require('./naruto_uzumaki.mp4'),
    obito_uchiha: require('./obito_uchiha.mp4'),
    pain_nagato: require('./pain_nagato.mp4'),
    ryomen_sukuna: require('./ryomen_sukuna.mp4'),
    satoru_gojo: require('./satoru_gojo.mp4'),
    sosuke_aizen: require('./sosuke_aizen.mp4'),
    yuta_okkotsu: require('./yuta_okkotsu.mp4'),
};
