import { AbilityType } from './types';

// خريطة لترجمة أسماء القدرات للعربية
export const ABILITY_NAMES_AR: Record<AbilityType, string> = {
  LogicalEncounter: 'مصادفة منطقية',
  Recall: 'استدعاء',
  Protection: 'حماية',
  Arise: 'أرايز',
  Reinforcement: 'التدعيم',
  Wipe: 'المسح',
  Purge: 'التطهير',
  HalvePoints: 'تنصيف النقاط',
  Seal: 'الختم',
  DoubleOrNothing: 'دبل أو لا شيء',
  StarSuperiority: 'تفوق النجوم',
  Reduction: 'التقليص',
  Sacrifice: 'تضحية',
  Popularity: 'الشعبية',
  Eclipse: 'الخسف',
  CancelAbility: 'إلغاء الخاصية',
  Revive: 'إنعاش',
  Shambles: 'شامبلز',
  ConsecutiveLossBuff: 'تعزيز الخسارة',
  Lifesteal: 'سرقة الحياة',
  Revenge: 'الانتقام',
  Suicide: 'الانتحار',
  Disaster: 'النكبة',
  Compensation: 'التعويض',
  Weakening: 'الإضعاف',
  Misdirection: 'التضليل',
  StealAbility: 'سرقة الخاصية',
  Rescue: 'الإنقاذ',
  Trap: 'الفخ',
  ConvertDebuffsToBuffs: 'تحويل السلبيات',
  Sniping: 'القنص',
  Merge: 'الدمج',
  DoubleNextCards: 'المضاعفة',
  Deprivation: 'السلب',
  Greed: 'الجشع',
  Dilemma: 'الورطة',
  Subhan: 'الصبحان',
  Propaganda: 'بروباغاندا',
  DoubleYourBuffs: 'مضاعفة البفات',
  Avatar: 'أفاتار',
  Penetration: 'الاختراق',
  Pool: 'المسبح',
  Conversion: 'التحويل',
  Shield: 'الدرع',
  SwapClass: 'تبديل الفئة',
  TakeIt: 'خذها',
  Skip: 'تخطي',
  AddElement: 'إضافة عنصر',
  Explosion: 'الانفجار',
  DoublePoints: 'مضاعفة النقاط',
  ElementalMastery: 'إتقان العناصر',
};

// دالة للحصول على اسم القدرة بالعربية
export function getAbilityNameAr(abilityType: AbilityType): string {
  return ABILITY_NAMES_AR[abilityType] || abilityType;
}
