export const RARE_IMAGES: Record<string, any> = {
    coby: require('./coby.png'),
    usopp: require('./usopp.png'),
    tony_tony_chopper: require('./tony_tony_chopper.png'),
    dende: require('./dende.png'),
    yamcha: require('./yamcha.png'),
    tien_shinhan: require('./tien_shinhan.png'),
    sasha_braus: require('./sasha_braus.png'),
    falco_grice: require('./falco_grice.png'),
    l_lawliet: require('./l_lawliet.png'),
    light_yagami: require('./light_yagami.png'),
    barry_the_chopper: require('./barry_the_chopper.png'),
    martel: require('./martel.png'),
    suspicious_beggar: require('./suspicious_beggar.png'),
    emlyn_white: require('./emlyn_white.png'),
    ram: require('./ram.png'),
    silica: require('./silica.png'),
    yui: require('./yui.png'),
    rundelhaus: require('./rundelhaus.png'),
    floki: require('./floki.png'),
    nia_teppelin: require('./nia_teppelin.png'),
    dr_cossack: require('./dr_cossack.png'),
};
