import type { Card } from '@/lib/game/types';

// ══════════════════════════════════════════════════════════
// كروت الأنمي — Anime Characters Cards
// ══════════════════════════════════════════════════════════

export const ANIME_CARDS: Card[] = [

  // ════════════════════════════════════════════════════
  // One Piece (25 cards)
  // ════════════════════════════════════════════════════
  {
    id: 'yosaku',
    name: 'Yosaku',
    nameAr: 'يوساكو',
    attack: 2, defense: 1,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'common', stars: 1,
    animationPreset: 'default',
  },
  {
    id: 'johnny',
    name: 'Johnny',
    nameAr: 'جوني',
    attack: 3, defense: 0,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'common', stars: 1,
    animationPreset: 'default',
  },
  {
    id: 'nami',
    name: 'Nami',
    nameAr: 'نامي',
    attack: 3, defense: 2,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'common', stars: 1,
    animationPreset: 'lightning',
  },
  {
    id: 'coby',
    name: 'Coby',
    nameAr: 'كوبي',
    attack: 6, defense: 6,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'usopp',
    name: 'Usopp',
    nameAr: 'أوسوب',
    attack: 8, defense: 6,
    race: 'human', cardClass: 'archer', element: 'wind',
    tags: ['bow'], emoji: '🏹',
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'tony_tony_chopper',
    name: 'Tony Tony Chopper',
    nameAr: 'توني توني تشوبر',
    attack: 9, defense: 6,
    race: 'monster', cardClass: 'berserker', element: 'ice',
    tags: ['sword'], emoji: '👹',
    rarity: 'rare', stars: 3,
    animationPreset: 'ice',
  },
  {
    id: 'franky',
    name: 'Franky',
    nameAr: 'فرانكي',
    attack: 13, defense: 11,
    race: 'robot', cardClass: 'warrior', element: 'lightning',
    tags: ['sword', 'shield'], emoji: '🤖',
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'eustass_kid',
    name: 'Eustass Kid',
    nameAr: 'يوستاس كيد',
    attack: 13, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'crocodile',
    name: 'Crocodile',
    nameAr: 'كروكودايل',
    attack: 14, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'donquixote_doflamingo',
    name: 'Donquixote Doflamingo',
    nameAr: 'دوفلامينغو',
    attack: 13, defense: 14,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'white_snake',
    name: 'White Snake',
    nameAr: 'الحية البيضاء',
    attack: 15, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'black_maria',
    name: 'Black Maria',
    nameAr: 'الحية السوداء',
    attack: 13, defense: 12,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'trafalgar_law',
    name: 'Trafalgar Law',
    nameAr: 'ترافلغار لاو',
    attack: 14, defense: 15,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'jinbe',
    name: 'Jinbe',
    nameAr: 'جينبي',
    attack: 16, defense: 16,
    race: 'monster', cardClass: 'berserker', element: 'water',
    tags: ['sword'], emoji: '👹',
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'sabo',
    name: 'Sabo',
    nameAr: 'سابو',
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'sanji',
    name: 'Sanji',
    nameAr: 'سانجي',
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'shiki',
    name: 'Shiki',
    nameAr: 'شيكي',
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'roronoa_zoro',
    name: 'Roronoa Zoro',
    nameAr: 'رورونوا زورو',
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'dracule_mihawk',
    name: 'Dracule Mihawk',
    nameAr: 'دراكيول ميهوك',
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'monkey_d_luffy',
    name: 'Monkey D. Luffy',
    nameAr: 'مونكي دي لوفي',
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'gol_d_roger',
    name: 'Gol D. Roger',
    nameAr: 'غول دي روجر',
    attack: 17, defense: 18,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'kaido',
    name: 'Kaido',
    nameAr: 'كايدو',
    attack: 19, defense: 16,
    race: 'dragon', cardClass: 'mage', element: 'fire',
    tags: ['magic'], emoji: '🐉',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },

  // ════════════════════════════════════════════════════
  // Naruto
  // ════════════════════════════════════════════════════
  {
    id: 'ebisu',
    name: 'Ebisu',
    nameAr: 'إيبيسو',
    attack: 3, defense: 0,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'common', stars: 1,
    animationPreset: 'default',
  },
  {
    id: 'konohamaru',
    name: 'Konohamaru',
    nameAr: 'كونوهامارو',
    attack: 5, defense: 0,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'common', stars: 2,
    animationPreset: 'fire',
  },
  {
    id: 'sakura_haruno',
    name: 'Sakura Haruno',
    nameAr: 'ساكورا هارونو',
    attack: 12, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'neji_hyuga',
    name: 'Neji Hyuga',
    nameAr: 'نيجي هيوغا',
    attack: 14, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'rock_lee',
    name: 'Rock Lee',
    nameAr: 'روك لي',
    attack: 13, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'killer_bee',
    name: 'Killer Bee',
    nameAr: 'كيلر بي',
    attack: 13, defense: 12,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'gaara',
    name: 'Gaara',
    nameAr: 'غارا',
    attack: 14, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'tsunade',
    name: 'Tsunade',
    nameAr: 'تسونادي',
    attack: 13, defense: 13,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'orochimaru',
    name: 'Orochimaru',
    nameAr: 'أوروتشيمارو',
    attack: 15, defense: 13,
    race: 'monster', cardClass: 'berserker', element: 'ice',
    tags: ['sword'], emoji: '👹',
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'kakashi_hatake',
    name: 'Kakashi Hatake',
    nameAr: 'كاكاشي هاتاكي',
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'jiraiya',
    name: 'Jiraiya',
    nameAr: 'جيرايا',
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'might_guy',
    name: 'Might Guy',
    nameAr: 'مايت غاي',
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'obito_uchiha',
    name: 'Obito Uchiha',
    nameAr: 'أوبيتو أوتشيها',
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'itachi_uchiha',
    name: 'Itachi Uchiha',
    nameAr: 'إيتاتشي أوتشيها',
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'pain_nagato',
    name: 'Pain (Nagato)',
    nameAr: 'باين (ناغاتو)',
    attack: 16, defense: 17,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'minato_namikaze',
    name: 'Minato Namikaze',
    nameAr: 'ميناتو ناميكازي',
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'sasuke_uchiha',
    name: 'Sasuke Uchiha',
    nameAr: 'ساسكي أوتشيها',
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'naruto_uzumaki',
    name: 'Naruto Uzumaki',
    nameAr: 'ناروتو أوزوماكي',
    attack: 19, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'madara_uchiha',
    name: 'Madara Uchiha',
    nameAr: 'مادارا أوتشيها',
    attack: 17, defense: 17,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'kaguya_otsutsuki',
    name: 'Kaguya Otsutsuki',
    nameAr: 'كاغويا أوتسوتسوكي',
    attack: 19, defense: 18,
    race: 'monster', cardClass: 'berserker', element: 'ice',
    tags: ['sword'], emoji: '👹',
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },

  // ════════════════════════════════════════════════════
  // Dragon Ball
  // ════════════════════════════════════════════════════
  {
    id: 'bulma',
    name: 'Bulma',
    nameAr: 'بولما',
    attack: 1, defense: 0,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'common', stars: 1,
    animationPreset: 'default',
  },
  {
    id: 'yamcha',
    name: 'Yamcha',
    nameAr: 'يامتشا',
    attack: 6, defense: 6,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'tien_shinhan',
    name: 'Tien Shinhan',
    nameAr: 'تيان شينهان',
    attack: 8, defense: 9,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'dende',
    name: 'Dende',
    nameAr: 'ديندي',
    attack: 6, defense: 6,
    race: 'elf', cardClass: 'archer', element: 'ice',
    tags: ['bow'], emoji: '🏹',
    rarity: 'rare', stars: 3,
    animationPreset: 'ice',
  },
  {
    id: 'krillin',
    name: 'Krillin',
    nameAr: 'كريلين',
    attack: 15, defense: 13,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'master_roshi',
    name: 'Master Roshi',
    nameAr: 'الماستر روشي',
    attack: 12, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'piccolo',
    name: 'Piccolo',
    nameAr: 'بيكولو',
    attack: 18, defense: 16,
    race: 'monster', cardClass: 'berserker', element: 'wind',
    tags: ['sword'], emoji: '👹',
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'syn_shenron',
    name: 'Syn Shenron',
    nameAr: 'سين شينرون',
    attack: 18, defense: 16,
    race: 'dragon', cardClass: 'mage', element: 'fire',
    tags: ['magic'], emoji: '🐉',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'trunks',
    name: 'Trunks',
    nameAr: 'ترانكس',
    attack: 17, defense: 16,
    race: 'monster', cardClass: 'berserker', element: 'lightning',
    tags: ['sword'], emoji: '👹',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'gohan',
    name: 'Gohan',
    nameAr: 'غوهان',
    attack: 16, defense: 16,
    race: 'monster', cardClass: 'berserker', element: 'lightning',
    tags: ['sword'], emoji: '👹',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'cell',
    name: 'Cell',
    nameAr: 'سيل',
    attack: 17, defense: 16,
    race: 'monster', cardClass: 'berserker', element: 'lightning',
    tags: ['sword'], emoji: '👹',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'frieza',
    name: 'Frieza',
    nameAr: 'فريزا',
    attack: 17, defense: 16,
    race: 'monster', cardClass: 'berserker', element: 'ice',
    tags: ['sword'], emoji: '👹',
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'vegeta',
    name: 'Vegeta',
    nameAr: 'فيجيتا',
    attack: 17, defense: 16,
    race: 'monster', cardClass: 'berserker', element: 'lightning',
    tags: ['sword'], emoji: '👹',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'broly',
    name: 'Broly',
    nameAr: 'بروللي',
    attack: 18, defense: 16,
    race: 'monster', cardClass: 'berserker', element: 'fire',
    tags: ['sword'], emoji: '👹',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'omega_shenron',
    name: 'Omega Shenron',
    nameAr: 'أوميغا شينرون',
    attack: 19, defense: 16,
    race: 'dragon', cardClass: 'mage', element: 'fire',
    tags: ['magic'], emoji: '🐉',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'son_goku',
    name: 'Son Goku',
    nameAr: 'غوكو',
    attack: 18, defense: 17,
    race: 'monster', cardClass: 'berserker', element: 'lightning',
    tags: ['sword'], emoji: '👹',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },

  // ════════════════════════════════════════════════════
  // Attack on Titan
  // ════════════════════════════════════════════════════
  {
    id: 'reiner_braun',
    name: 'Reiner Braun',
    nameAr: 'راينر براون',
    attack: 16, defense: 16,
    race: 'monster', cardClass: 'berserker', element: 'earth',
    tags: ['sword'], emoji: '👹',
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'zeke_yeager',
    name: 'Zeke Yeager',
    nameAr: 'زيك ييغر',
    attack: 16, defense: 16,
    race: 'monster', cardClass: 'berserker', element: 'lightning',
    tags: ['sword'], emoji: '👹',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'eren_yeager',
    name: 'Eren Yeager',
    nameAr: 'إيرين ييغر',
    attack: 16, defense: 17,
    race: 'monster', cardClass: 'berserker', element: 'fire',
    tags: ['sword'], emoji: '👹',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'levi_ackerman',
    name: 'Levi Ackerman',
    nameAr: 'ليفي أكرمان',
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },

  // ════════════════════════════════════════════════════
  // Demon Slayer
  // ════════════════════════════════════════════════════
  {
    id: 'tengen_uzui',
    name: 'Tengen Uzui',
    nameAr: 'تينغين أوزوي',
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'kyojuro_rengoku',
    name: 'Kyojuro Rengoku',
    nameAr: 'كوجورو رينغوكو',
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'muichiro_tokito',
    name: 'Muichiro Tokito',
    nameAr: 'مويتشيرو توكيتو',
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'giyu_tomioka',
    name: 'Giyu Tomioka',
    nameAr: 'غيو توميوكا',
    attack: 16, defense: 17,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'doma',
    name: 'Doma',
    nameAr: 'دوما',
    attack: 16, defense: 16,
    race: 'demon', cardClass: 'berserker', element: 'ice',
    tags: ['sword'], emoji: '😈',
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'kokushibo',
    name: 'Kokushibo',
    nameAr: 'كوكوشيبو',
    attack: 17, defense: 16,
    race: 'demon', cardClass: 'berserker', element: 'ice',
    tags: ['sword'], emoji: '😈',
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'akaza',
    name: 'Akaza',
    nameAr: 'أكازا',
    attack: 18, defense: 16,
    race: 'demon', cardClass: 'berserker', element: 'fire',
    tags: ['sword'], emoji: '😈',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'muzan_kibutsuji',
    name: 'Muzan Kibutsuji',
    nameAr: 'موزان كيبوتسوجي',
    attack: 18, defense: 16,
    race: 'demon', cardClass: 'berserker', element: 'ice',
    tags: ['sword'], emoji: '😈',
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },

  // ════════════════════════════════════════════════════
  // Hunter x Hunter
  // ════════════════════════════════════════════════════
  {
    id: 'gon_freecss',
    name: 'Gon Freecss',
    nameAr: 'غون فريكس',
    attack: 16, defense: 17,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'killua_zoldyck',
    name: 'Killua Zoldyck',
    nameAr: 'كيلوا زولديك',
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'chrollo_lucilfer',
    name: 'Chrollo Lucilfer',
    nameAr: 'كرولو لوسيلفر',
    attack: 16, defense: 17,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'hisoka_morow',
    name: 'Hisoka Morow',
    nameAr: 'هيسوكا مورو',
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'isaac_netero',
    name: 'Isaac Netero',
    nameAr: 'إسحاق نيتيرو',
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'meruem',
    name: 'Meruem',
    nameAr: 'ميريوم',
    attack: 17, defense: 18,
    race: 'monster', cardClass: 'berserker', element: 'lightning',
    tags: ['sword'], emoji: '👹',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },

  // ════════════════════════════════════════════════════
  // Jujutsu Kaisen
  // ════════════════════════════════════════════════════
  {
    id: 'yuji_itadori',
    name: 'Yuji Itadori',
    nameAr: 'يوجي إيتادوري',
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'megumi_fushiguro',
    name: 'Megumi Fushiguro',
    nameAr: 'ميغومي فوشيغورو',
    attack: 14, defense: 14,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'nobara_kugisaki',
    name: 'Nobara Kugisaki',
    nameAr: 'نوبارا كوغيساكي',
    attack: 13, defense: 12,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'suguru_geto',
    name: 'Suguru Geto',
    nameAr: 'سوغورو غيتو',
    attack: 15, defense: 14,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'yuta_okkotsu',
    name: 'Yuta Okkotsu',
    nameAr: 'يوتا أوكوتسو',
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'ryomen_sukuna',
    name: 'Ryomen Sukuna',
    nameAr: 'ريومن سوكونا',
    attack: 19, defense: 16,
    race: 'demon', cardClass: 'berserker', element: 'fire',
    tags: ['sword'], emoji: '😈',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'satoru_gojo',
    name: 'Satoru Gojo',
    nameAr: 'ساتورو غوجو',
    attack: 17, defense: 18,
    race: 'human', cardClass: 'mage', element: 'ice',
    tags: ['magic'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },

  // ════════════════════════════════════════════════════
  // Bleach
  // ════════════════════════════════════════════════════
  {
    id: 'ichigo_kurosaki',
    name: 'Ichigo Kurosaki',
    nameAr: 'إيتشيغو كوروساكي',
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'sosuke_aizen',
    name: 'Sosuke Aizen',
    nameAr: 'سوسوكي آيزن',
    attack: 16, defense: 17,
    race: 'human', cardClass: 'mage', element: 'ice',
    tags: ['magic'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'byakuya_kuchiki',
    name: 'Byakuya Kuchiki',
    nameAr: 'بياكويا كوتشيكي',
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'grimmjow_jaegerjaquez',
    name: 'Grimmjow Jaegerjaquez',
    nameAr: 'غريمجو جاغرجاكيز',
    attack: 17, defense: 15,
    race: 'demon', cardClass: 'berserker', element: 'lightning',
    tags: ['sword'], emoji: '😈',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'ulquiorra_cifer',
    name: 'Ulquiorra Cifer',
    nameAr: 'أولكويورا سيفر',
    attack: 16, defense: 17,
    race: 'demon', cardClass: 'berserker', element: 'ice',
    tags: ['sword'], emoji: '😈',
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'kenpachi_zaraki',
    name: 'Kenpachi Zaraki',
    nameAr: 'كينباتشي زاراكي',
    attack: 18, defense: 14,
    race: 'human', cardClass: 'berserker', element: 'fire',
    tags: ['sword'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },

  // ════════════════════════════════════════════════════
  // My Hero Academia
  // ════════════════════════════════════════════════════
  {
    id: 'izuku_midoriya',
    name: 'Izuku Midoriya',
    nameAr: 'إيزوكو ميدوريا',
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'katsuki_bakugo',
    name: 'Katsuki Bakugo',
    nameAr: 'كاتسوكي باكوغو',
    attack: 15, defense: 13,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'all_might',
    name: 'All Might',
    nameAr: 'أول مايت',
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'tomura_shigaraki',
    name: 'Tomura Shigaraki',
    nameAr: 'تومورا شيغاراكي',
    attack: 17, defense: 15,
    race: 'demon', cardClass: 'berserker', element: 'ice',
    tags: ['sword'], emoji: '😈',
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'endeavor',
    name: 'Endeavor',
    nameAr: 'إنديفور',
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },

  // ════════════════════════════════════════════════════
  // Death Note
  // ════════════════════════════════════════════════════
  {
    id: 'ryuk',
    name: 'Ryuk',
    nameAr: 'ريوك',
    attack: 17, defense: 16,
    race: 'demon', cardClass: 'berserker', element: 'ice',
    tags: ['sword'], emoji: '😈',
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    // ✅ بطاقة ميسا أمان — الفيديو مربوط تلقائياً عبر COMMON_VIDEOS
    id: 'misa_amane',
    name: 'Misa Amane',
    nameAr: 'ميسا أمان',
    attack: 7, defense: 5,
    race: 'human', cardClass: 'mage', element: 'ice',
    tags: ['magic'], emoji: '🖤',
    rarity: 'common', stars: 2,
    animationPreset: 'shadow',
    specialAbility: 'عيون الموت — ترى رقم الجولة القادمة للخصم',
    rageMode: {
      enabled: true,
      rageNameAr: 'عيون الشينيغامي',
      rageAttackBoost: 10,
      rageDefenseBoost: 6,
      oncePer: 'match',
    },
  },

  // ════════════════════════════════════════════════════
  // Chainsaw Man
  // ════════════════════════════════════════════════════
  {
    id: 'denji',
    name: 'Denji',
    nameAr: 'دينجي',
    attack: 16, defense: 14,
    race: 'human', cardClass: 'berserker', element: 'fire',
    tags: ['sword'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'makima',
    name: 'Makima',
    nameAr: 'ماكيما',
    attack: 17, defense: 17,
    race: 'demon', cardClass: 'mage', element: 'ice',
    tags: ['magic'], emoji: '😈',
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'power',
    name: 'Power',
    nameAr: 'باور',
    attack: 15, defense: 13,
    race: 'demon', cardClass: 'berserker', element: 'fire',
    tags: ['sword'], emoji: '😈',
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },

  // ════════════════════════════════════════════════════
  // One Punch Man
  // ════════════════════════════════════════════════════
  {
    id: 'saitama',
    name: 'Saitama',
    nameAr: 'سايتاما',
    attack: 20, defense: 10,
    race: 'human', cardClass: 'berserker', element: 'lightning',
    tags: ['sword'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    specialAbility: 'ضربة واحدة — يتجاوز الدفاع كاملاً مرة واحدة',
    animationPreset: 'lightning',
  },
  {
    id: 'genos',
    name: 'Genos',
    nameAr: 'جينوس',
    attack: 16, defense: 14,
    race: 'robot', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '🤖',
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
];
