import type { Card } from '@/lib/game/types';

// ══════════════════════════════════════════════════════════
// كروت الأنمي — Anime Characters Cards
// أضف هذا الملف في مجلد lib/game/
// ثم في cards-data.ts أضف: import { ANIME_CARDS } from './anime-cards-data';
// وفي ALL_CARDS: ...ANIME_CARDS,
// ══════════════════════════════════════════════════════════

export const ANIME_CARDS: Card[] = [

  // ════════════════════════════════════════════════════
  // One Piece (25 cards)
  // ════════════════════════════════════════════════════
  {
    id: 'yosaku',
    name: 'Yosaku',
    nameAr: 'يوساكو',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/2/284121.jpg',
    attack: 2, defense: 1,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'common', stars: 1,
    animationPreset: 'default',
  },
  {
    id: 'johnny',
    name: 'Johnny',
    nameAr: 'جوني',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/2/284122.jpg',
    attack: 3, defense: 0,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'common', stars: 1,
    animationPreset: 'default',
  },
  {
    id: 'nami',
    name: 'Nami',
    nameAr: 'نامي',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/5/275305.jpg',
    attack: 3, defense: 2,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'common', stars: 1,
    animationPreset: 'lightning',
  },
  {
    id: 'coby',
    name: 'Coby',
    nameAr: 'كوبي',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/2/284119.jpg',
    attack: 6, defense: 6,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'usopp',
    name: 'Usopp',
    nameAr: 'أوسوب',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/9/275300.jpg',
    attack: 8, defense: 6,
    race: 'human', cardClass: 'archer', element: 'wind',
    tags: ['bow'], emoji: '🏹',
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'tony_tony_chopper',
    name: 'Tony Tony Chopper',
    nameAr: 'توني توني تشوبر',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/3/275297.jpg',
    attack: 9, defense: 6,
    race: 'monster', cardClass: 'berserker', element: 'ice',
    tags: ['sword'], emoji: '👹',
    rarity: 'rare', stars: 3,
    animationPreset: 'ice',
  },
  {
    id: 'nico_robin',
    name: 'Nico Robin',
    nameAr: 'نيكو روبين',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/7/275298.jpg',
    attack: 12, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'brook',
    name: 'Brook',
    nameAr: 'بروك',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/6/275299.jpg',
    attack: 11, defense: 11,
    race: 'undead', cardClass: 'knight', element: 'ice',
    tags: ['sword', 'shield'], emoji: '💀',
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'franky',
    name: 'Franky',
    nameAr: 'فرانكي',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/8/275296.jpg',
    attack: 13, defense: 11,
    race: 'robot', cardClass: 'warrior', element: 'lightning',
    tags: ['sword', 'shield'], emoji: '🤖',
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'eustass_kid',
    name: 'Eustass Kid',
    nameAr: 'يوستاس كيد',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/16/352336.jpg',
    attack: 13, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'crocodile',
    name: 'Crocodile',
    nameAr: 'كروكودايل',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/14/299498.jpg',
    attack: 14, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'donquixote_doflamingo',
    name: 'Donquixote Doflamingo',
    nameAr: 'دوفلامينغو',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/15/357843.jpg',
    attack: 13, defense: 14,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'white_snake',
    name: 'White Snake',
    nameAr: 'الحية البيضاء',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/2/284120.jpg',
    attack: 15, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'boa_hancock',
    name: 'Boa Hancock',
    nameAr: 'بوا هانكوك',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/11/298787.jpg',
    attack: 13, defense: 14,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'black_maria',
    name: 'Black Maria',
    nameAr: 'الحية السوداء',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/12/438765.jpg',
    attack: 13, defense: 12,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'trafalgar_law',
    name: 'Trafalgar Law',
    nameAr: 'ترافلغار لاو',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/4/349777.jpg',
    attack: 14, defense: 15,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'jinbe',
    name: 'Jinbe',
    nameAr: 'جينبي',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/13/349776.jpg',
    attack: 16, defense: 16,
    race: 'monster', cardClass: 'berserker', element: 'water',
    tags: ['sword'], emoji: '👹',
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'sabo',
    name: 'Sabo',
    nameAr: 'سابو',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/14/357842.jpg',
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'sanji',
    name: 'Sanji',
    nameAr: 'سانجي',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/10/298786.jpg',
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'shiki',
    name: 'Shiki',
    nameAr: 'شيكي',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/9/353785.jpg',
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'roronoa_zoro',
    name: 'Roronoa Zoro',
    nameAr: 'رورونوا زورو',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/2/275302.jpg',
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'dracule_mihawk',
    name: 'Dracule Mihawk',
    nameAr: 'دراكيول ميهوك',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/5/298785.jpg',
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'monkey_d_luffy',
    name: 'Monkey D. Luffy',
    nameAr: 'مونكي دي لوفي',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/9/310307.jpg',
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'gol_d_roger',
    name: 'Gol D. Roger',
    nameAr: 'غول دي روجر',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/7/298783.jpg',
    attack: 17, defense: 18,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'kaido',
    name: 'Kaido',
    nameAr: 'كايدو',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/8/406899.jpg',
    attack: 19, defense: 16,
    race: 'dragon', cardClass: 'mage', element: 'fire',
    tags: ['magic'], emoji: '🐉',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },

  // ════════════════════════════════════════════════════
  // Naruto
  // ════════════════════════════════════════════════════
  {
    id: 'ebisu',
    name: 'Ebisu',
    nameAr: 'إيبيسو',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/6/284118.jpg',
    attack: 3, defense: 0,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'common', stars: 1,
    animationPreset: 'default',
  },
  {
    id: 'konohamaru',
    name: 'Konohamaru',
    nameAr: 'كونوهامارو',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/11/298789.jpg',
    attack: 5, defense: 0,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'common', stars: 2,
    animationPreset: 'fire',
  },
  {
    id: 'sakura_haruno',
    name: 'Sakura Haruno',
    nameAr: 'ساكورا هارونو',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/11/174116.jpg',
    attack: 12, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'neji_hyuga',
    name: 'Neji Hyuga',
    nameAr: 'نيجي هيوغا',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/15/174115.jpg',
    attack: 14, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'rock_lee',
    name: 'Rock Lee',
    nameAr: 'روك لي',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/9/174114.jpg',
    attack: 13, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'killer_bee',
    name: 'Killer Bee',
    nameAr: 'كيلر بي',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/10/299495.jpg',
    attack: 13, defense: 12,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'gaara',
    name: 'Gaara',
    nameAr: 'غارا',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/7/174113.jpg',
    attack: 14, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'tsunade',
    name: 'Tsunade',
    nameAr: 'تسونادي',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/8/174112.jpg',
    attack: 13, defense: 13,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'orochimaru',
    name: 'Orochimaru',
    nameAr: 'أوروتشيمارو',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/6/174111.jpg',
    attack: 15, defense: 13,
    race: 'monster', cardClass: 'berserker', element: 'ice',
    tags: ['sword'], emoji: '👹',
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'kakashi_hatake',
    name: 'Kakashi Hatake',
    nameAr: 'كاكاشي هاتاكي',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/7/284652.jpg',
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'jiraiya',
    name: 'Jiraiya',
    nameAr: 'جيرايا',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/8/174110.jpg',
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'might_guy',
    name: 'Might Guy',
    nameAr: 'مايت غاي',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/12/174109.jpg',
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'obito_uchiha',
    name: 'Obito Uchiha',
    nameAr: 'أوبيتو أوتشيها',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/14/299494.jpg',
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'itachi_uchiha',
    name: 'Itachi Uchiha',
    nameAr: 'إيتاتشي أوتشيها',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/5/174108.jpg',
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'pain_nagato',
    name: 'Pain (Nagato)',
    nameAr: 'باين (ناغاتو)',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/13/174107.jpg',
    attack: 16, defense: 17,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'minato_namikaze',
    name: 'Minato Namikaze',
    nameAr: 'ميناتو ناميكازي',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/11/174106.jpg',
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'sasuke_uchiha',
    name: 'Sasuke Uchiha',
    nameAr: 'ساسكي أوتشيها',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/10/174105.jpg',
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'naruto_uzumaki',
    name: 'Naruto Uzumaki',
    nameAr: 'ناروتو أوزوماكي',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/9/310306.jpg',
    attack: 19, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'madara_uchiha',
    name: 'Madara Uchiha',
    nameAr: 'مادارا أوتشيها',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/13/299493.jpg',
    attack: 17, defense: 17,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'kaguya_otsutsuki',
    name: 'Kaguya Otsutsuki',
    nameAr: 'كاغويا أوتسوتسوكي',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/4/357841.jpg',
    attack: 19, defense: 18,
    race: 'monster', cardClass: 'berserker', element: 'ice',
    tags: ['sword'], emoji: '👹',
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },

  // ════════════════════════════════════════════════════
  // Dragon Ball
  // ════════════════════════════════════════════════════
  {
    id: 'bulma',
    name: 'Bulma',
    nameAr: 'بولما',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/2/73831.jpg',
    attack: 1, defense: 0,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'common', stars: 1,
    animationPreset: 'default',
  },
  {
    id: 'yamcha',
    name: 'Yamcha',
    nameAr: 'يامتشا',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/6/73836.jpg',
    attack: 6, defense: 6,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'tien_shinhan',
    name: 'Tien Shinhan',
    nameAr: 'تيان شينهان',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/10/73840.jpg',
    attack: 8, defense: 9,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'dende',
    name: 'Dende',
    nameAr: 'ديندي',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/9/73839.jpg',
    attack: 6, defense: 6,
    race: 'elf', cardClass: 'archer', element: 'ice',
    tags: ['bow'], emoji: '🏹',
    rarity: 'rare', stars: 3,
    animationPreset: 'ice',
  },
  {
    id: 'krillin',
    name: 'Krillin',
    nameAr: 'كريلين',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/7/73837.jpg',
    attack: 15, defense: 13,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'nail',
    name: 'Nail',
    nameAr: 'نيل',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/11/73841.jpg',
    attack: 14, defense: 14,
    race: 'elf', cardClass: 'archer', element: 'wind',
    tags: ['bow'], emoji: '🏹',
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'master_roshi',
    name: 'Master Roshi',
    nameAr: 'الماستر روشي',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/8/73838.jpg',
    attack: 12, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'lord_slug',
    name: 'Lord Slug',
    nameAr: 'اللورد سلوغ',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/12/73842.jpg',
    attack: 14, defense: 11,
    race: 'elf', cardClass: 'archer', element: 'ice',
    tags: ['bow'], emoji: '🏹',
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'rage_shenron',
    name: 'Rage Shenron',
    nameAr: 'راج شينرون',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/13/73843.jpg',
    attack: 14, defense: 11,
    race: 'dragon', cardClass: 'mage', element: 'fire',
    tags: ['magic'], emoji: '🐉',
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'piccolo',
    name: 'Piccolo',
    nameAr: 'بيكولو',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/3/73833.jpg',
    attack: 18, defense: 16,
    race: 'monster', cardClass: 'berserker', element: 'wind',
    tags: ['sword'], emoji: '👹',
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'syn_shenron',
    name: 'Syn Shenron',
    nameAr: 'سين شينرون',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/14/73844.jpg',
    attack: 18, defense: 16,
    race: 'dragon', cardClass: 'mage', element: 'fire',
    tags: ['magic'], emoji: '🐉',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'trunks',
    name: 'Trunks',
    nameAr: 'ترانكس',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/5/73835.jpg',
    attack: 17, defense: 16,
    race: 'monster', cardClass: 'berserker', element: 'lightning',
    tags: ['sword'], emoji: '👹',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'gohan',
    name: 'Gohan',
    nameAr: 'غوهان',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/4/73834.jpg',
    attack: 16, defense: 16,
    race: 'monster', cardClass: 'berserker', element: 'lightning',
    tags: ['sword'], emoji: '👹',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'cell',
    name: 'Cell',
    nameAr: 'سيل',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/6/73844.jpg',
    attack: 17, defense: 16,
    race: 'monster', cardClass: 'berserker', element: 'lightning',
    tags: ['sword'], emoji: '👹',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'frieza',
    name: 'Frieza',
    nameAr: 'فريزا',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/6/73832.jpg',
    attack: 17, defense: 16,
    race: 'monster', cardClass: 'berserker', element: 'ice',
    tags: ['sword'], emoji: '👹',
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'vegeta',
    name: 'Vegeta',
    nameAr: 'فيجيتا',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/3/310305.jpg',
    attack: 17, defense: 16,
    race: 'monster', cardClass: 'berserker', element: 'lightning',
    tags: ['sword'], emoji: '👹',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'broly',
    name: 'Broly',
    nameAr: 'بروللي',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/7/406898.jpg',
    attack: 18, defense: 16,
    race: 'monster', cardClass: 'berserker', element: 'fire',
    tags: ['sword'], emoji: '👹',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'omega_shenron',
    name: 'Omega Shenron',
    nameAr: 'أوميغا شينرون',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/15/73845.jpg',
    attack: 19, defense: 16,
    race: 'dragon', cardClass: 'mage', element: 'fire',
    tags: ['magic'], emoji: '🐉',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'son_goku',
    name: 'Son Goku',
    nameAr: 'غوكو',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/2/310304.jpg',
    attack: 18, defense: 17,
    race: 'monster', cardClass: 'berserker', element: 'lightning',
    tags: ['sword'], emoji: '👹',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },

  // ════════════════════════════════════════════════════
  // Attack on Titan
  // ════════════════════════════════════════════════════
  {
    id: 'reiner_braun',
    name: 'Reiner Braun',
    nameAr: 'راينر براون',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/12/311840.jpg',
    attack: 16, defense: 16,
    race: 'monster', cardClass: 'berserker', element: 'earth',
    tags: ['sword'], emoji: '👹',
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'zeke_yeager',
    name: 'Zeke Yeager',
    nameAr: 'زيك ييغر',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/13/311841.jpg',
    attack: 16, defense: 16,
    race: 'monster', cardClass: 'berserker', element: 'lightning',
    tags: ['sword'], emoji: '👹',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'eren_yeager',
    name: 'Eren Yeager',
    nameAr: 'إيرين ييغر',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/10/310309.jpg',
    attack: 16, defense: 17,
    race: 'monster', cardClass: 'berserker', element: 'fire',
    tags: ['sword'], emoji: '👹',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'levi_ackerman',
    name: 'Levi Ackerman',
    nameAr: 'ليفي أكرمان',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/11/310310.jpg',
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },

  // ════════════════════════════════════════════════════
  // Demon Slayer
  // ════════════════════════════════════════════════════
  {
    id: 'tengen_uzui',
    name: 'Tengen Uzui',
    nameAr: 'تينغين أوزوي',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/4/438762.jpg',
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'kyojuro_rengoku',
    name: 'Kyojuro Rengoku',
    nameAr: 'كوجورو رينغوكو',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/5/438763.jpg',
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'muichiro_tokito',
    name: 'Muichiro Tokito',
    nameAr: 'مويتشيرو توكيتو',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/6/438764.jpg',
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'giyu_tomioka',
    name: 'Giyu Tomioka',
    nameAr: 'غيو توميوكا',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/7/406900.jpg',
    attack: 16, defense: 17,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'doma',
    name: 'Doma',
    nameAr: 'دوما',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/8/438766.jpg',
    attack: 16, defense: 16,
    race: 'demon', cardClass: 'berserker', element: 'ice',
    tags: ['sword'], emoji: '😈',
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'kokushibo',
    name: 'Kokushibo',
    nameAr: 'كوكوشيبو',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/9/438767.jpg',
    attack: 17, defense: 16,
    race: 'demon', cardClass: 'berserker', element: 'ice',
    tags: ['sword'], emoji: '😈',
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'akaza',
    name: 'Akaza',
    nameAr: 'أكازا',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/10/438768.jpg',
    attack: 18, defense: 16,
    race: 'demon', cardClass: 'berserker', element: 'fire',
    tags: ['sword'], emoji: '😈',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'muzan_kibutsuji',
    name: 'Muzan Kibutsuji',
    nameAr: 'موزان كيبوتسوجي',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/11/406901.jpg',
    attack: 18, defense: 16,
    race: 'demon', cardClass: 'berserker', element: 'ice',
    tags: ['sword'], emoji: '😈',
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },

  // ════════════════════════════════════════════════════
  // Hunter x Hunter
  // ════════════════════════════════════════════════════
  {
    id: 'gon_freecss',
    name: 'Gon Freecss',
    nameAr: 'غون فريكس',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/8/284657.jpg',
    attack: 16, defense: 17,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'killua_zoldyck',
    name: 'Killua Zoldyck',
    nameAr: 'كيلوا زولديك',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/9/284658.jpg',
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'chrollo_lucilfer',
    name: 'Chrollo Lucilfer',
    nameAr: 'كرولو لوسيلفر',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/10/284659.jpg',
    attack: 16, defense: 17,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'hisoka_morow',
    name: 'Hisoka Morow',
    nameAr: 'هيسوكا مورو',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/11/284660.jpg',
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'isaac_netero',
    name: 'Isaac Netero',
    nameAr: 'إسحاق نيتيرو',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/12/284661.jpg',
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'meruem',
    name: 'Meruem',
    nameAr: 'ميريوم',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/13/352337.jpg',
    attack: 17, defense: 18,
    race: 'monster', cardClass: 'berserker', element: 'lightning',
    tags: ['sword'], emoji: '👹',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },

  // ════════════════════════════════════════════════════
  // Jujutsu Kaisen
  // ════════════════════════════════════════════════════
  {
    id: 'yuji_itadori',
    name: 'Yuji Itadori',
    nameAr: 'يوجي إيتادوري',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/2/457508.jpg',
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'megumi_fushiguro',
    name: 'Megumi Fushiguro',
    nameAr: 'ميغومي فوشيغورو',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/3/457509.jpg',
    attack: 14, defense: 14,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'nobara_kugisaki',
    name: 'Nobara Kugisaki',
    nameAr: 'نوبارا كوغيساكي',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/4/457510.jpg',
    attack: 13, defense: 12,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'suguru_geto',
    name: 'Suguru Geto',
    nameAr: 'سوغورو غيتو',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/5/457511.jpg',
    attack: 15, defense: 14,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'yuta_okkotsu',
    name: 'Yuta Okkotsu',
    nameAr: 'يوتا أوكوتسو',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/6/457512.jpg',
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'ryomen_sukuna',
    name: 'Ryomen Sukuna',
    nameAr: 'ريومن سوكونا',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/7/457513.jpg',
    attack: 19, defense: 16,
    race: 'demon', cardClass: 'berserker', element: 'fire',
    tags: ['sword'], emoji: '😈',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'satoru_gojo',
    name: 'Satoru Gojo',
    nameAr: 'ساتورو غوجو',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/8/457514.jpg',
    attack: 17, defense: 18,
    race: 'human', cardClass: 'mage', element: 'ice',
    tags: ['magic'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },

  // ════════════════════════════════════════════════════
  // Bleach
  // ════════════════════════════════════════════════════
  {
    id: 'ichigo_kurosaki',
    name: 'Ichigo Kurosaki',
    nameAr: 'إيتشيغو كوروساكي',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/5/53769.jpg',
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'sosuke_aizen',
    name: 'Sosuke Aizen',
    nameAr: 'سوسوكي آيزن',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/6/53770.jpg',
    attack: 16, defense: 17,
    race: 'human', cardClass: 'mage', element: 'ice',
    tags: ['magic'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'byakuya_kuchiki',
    name: 'Byakuya Kuchiki',
    nameAr: 'بياكويا كوتشيكي',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/7/53771.jpg',
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'grimmjow_jaegerjaquez',
    name: 'Grimmjow Jaegerjaquez',
    nameAr: 'غريمجو جاغرجاكيز',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/8/53772.jpg',
    attack: 17, defense: 15,
    race: 'demon', cardClass: 'berserker', element: 'lightning',
    tags: ['sword'], emoji: '😈',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'ulquiorra_cifer',
    name: 'Ulquiorra Cifer',
    nameAr: 'أولكويورا سيفر',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/9/53773.jpg',
    attack: 16, defense: 17,
    race: 'demon', cardClass: 'berserker', element: 'ice',
    tags: ['sword'], emoji: '😈',
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'kenpachi_zaraki',
    name: 'Kenpachi Zaraki',
    nameAr: 'كينباتشي زاراكي',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/10/53774.jpg',
    attack: 18, defense: 14,
    race: 'human', cardClass: 'berserker', element: 'fire',
    tags: ['sword'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },

  // ════════════════════════════════════════════════════
  // My Hero Academia
  // ════════════════════════════════════════════════════
  {
    id: 'izuku_midoriya',
    name: 'Izuku Midoriya',
    nameAr: 'إيزوكو ميدوريا',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/2/350537.jpg',
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'katsuki_bakugo',
    name: 'Katsuki Bakugo',
    nameAr: 'كاتسوكي باكوغو',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/3/350538.jpg',
    attack: 15, defense: 13,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'all_might',
    name: 'All Might',
    nameAr: 'أول مايت',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/4/350539.jpg',
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'tomura_shigaraki',
    name: 'Tomura Shigaraki',
    nameAr: 'تومورا شيغاراكي',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/5/350540.jpg',
    attack: 17, defense: 15,
    race: 'demon', cardClass: 'berserker', element: 'ice',
    tags: ['sword'], emoji: '😈',
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'endeavor',
    name: 'Endeavor',
    nameAr: 'إنديفور',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/6/350541.jpg',
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },

  // ════════════════════════════════════════════════════
  // Death Note
  // ════════════════════════════════════════════════════
  {
    id: 'ryuk',
    name: 'Ryuk',
    nameAr: 'ريوك',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/4/53777.jpg',
    attack: 17, defense: 16,
    race: 'demon', cardClass: 'berserker', element: 'ice',
    tags: ['sword'], emoji: '😈',
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },

  // ════════════════════════════════════════════════════
  // Chainsaw Man
  // ════════════════════════════════════════════════════
  {
    id: 'denji',
    name: 'Denji',
    nameAr: 'دينجي',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/2/496696.jpg',
    attack: 16, defense: 14,
    race: 'human', cardClass: 'berserker', element: 'fire',
    tags: ['sword'], emoji: '⚔️',
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'makima',
    name: 'Makima',
    nameAr: 'ماكيما',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/3/496697.jpg',
    attack: 17, defense: 17,
    race: 'demon', cardClass: 'mage', element: 'ice',
    tags: ['magic'], emoji: '😈',
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'power',
    name: 'Power',
    nameAr: 'باور',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/4/496698.jpg',
    attack: 15, defense: 13,
    race: 'demon', cardClass: 'berserker', element: 'fire',
    tags: ['sword'], emoji: '😈',
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },

  // ════════════════════════════════════════════════════
  // One Punch Man
  // ════════════════════════════════════════════════════
  {
    id: 'saitama',
    name: 'Saitama',
    nameAr: 'سايتاما',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/10/349997.jpg',
    attack: 20, defense: 10,
    race: 'human', cardClass: 'berserker', element: 'lightning',
    tags: ['sword'], emoji: '⚔️',
    rarity: 'legendary', stars: 5,
    specialAbility: 'ضربة واحدة — يتجاوز الدفاع كاملاً مرة واحدة',
    animationPreset: 'lightning',
  },
  {
    id: 'genos',
    name: 'Genos',
    nameAr: 'جينوس',
    imageUrl: 'https://cdn.myanimelist.net/images/characters/11/349998.jpg',
    attack: 16, defense: 14,
    race: 'robot', cardClass: 'warrior', element: 'fire',
    tags: ['sword', 'shield'], emoji: '🤖',
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
];
