import { Card, Element, ElementAdvantage, Effect, ELEMENT_ADVANTAGES, ELEMENT_WEAKNESSES, ELEMENT_MULTIPLIER } from './types';

// Batch 4/6 — Cards 139 to 184
// Universes: MHA, OPM, Bloodborne, LotM, Blue Exorcist, Diablo (Game), Helltaker, Chainsaw Man, Re:Zero

export const CARDS_BATCH_4: Card[] = [
  {
    id: 'shoto_todoroki',
    name: 'Shoto Todoroki',
    nameAr: 'شوتو تودوروكي',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 12, defense: 12,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'endeavor',
    name: 'Endeavor',
    nameAr: 'إنديفر',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 14, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'katsuki_bakugo',
    name: 'Katsuki Bakugo',
    nameAr: 'كاتسوكي باكوغو',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 15, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'izuku_midoriya',
    name: 'Izuku Midoriya',
    nameAr: 'إيزوكو ميدوريا',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 14, defense: 15,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'tomura_shigaraki',
    name: 'Tomura Shigaraki',
    nameAr: 'توموروا شيغاراكي',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 14, defense: 15,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'all_might',
    name: 'All Might',
    nameAr: 'أول مايت',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'king',
    name: 'King',
    nameAr: 'كينغ',
    finalImage: require('../../assets/cards/final/human-warrior.png'),
    attack: 1, defense: 0,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'common', stars: 1,
    animationPreset: 'lightning',
  },
  {
    id: 'genos',
    name: 'Genos',
    nameAr: 'جينوس',
    finalImage: require('../../assets/cards/final/human-mage.png'), // TODO: missing image
    attack: 12, defense: 11,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'bang',
    name: 'Bang',
    nameAr: 'بانغ',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 15, defense: 12,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'garou',
    name: 'Garou',
    nameAr: 'غارو',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'tatsumaki',
    name: 'Tatsumaki',
    nameAr: 'تاتسوماكي',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'saitama',
    name: 'Saitama',
    nameAr: 'سايتاما',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 17, defense: 17,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'the_plain_doll',
    name: 'The Plain Doll',
    nameAr: 'الدمية',
    finalImage: require('../../assets/cards/final/human-mage.png'),
    attack: 3, defense: 0,
    race: 'human', cardClass: 'mage', element: 'water',
    tags: ["magic"],
    rarity: 'common', stars: 1,
    animationPreset: 'default',
  },
  {
    id: 'suspicious_beggar',
    name: 'Suspicious Beggar',
    nameAr: 'المتسول المشبوه',
    finalImage: require('../../assets/cards/final/orc-warrior.png'), // TODO: missing image
    attack: 9, defense: 7,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'eileen_the_crow',
    name: 'Eileen the Crow',
    nameAr: 'إيلين الغراب',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 12, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'queen_annalise',
    name: 'Queen Annalise',
    nameAr: 'الملكة أناليس',
    finalImage: require('../../assets/cards/final/human-knight.png'), // TODO: missing image
    attack: 14, defense: 11,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'father_gascoigne',
    name: 'Father Gascoigne',
    nameAr: 'الأب غاسكوين',
    finalImage: require('../../assets/cards/final/orc-warrior.png'), // TODO: missing image
    attack: 14, defense: 11,
    race: 'orc', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'the_hunter',
    name: 'The Hunter',
    nameAr: 'الصياد',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 18, defense: 16,
    race: 'human', cardClass: 'archer', element: 'ice',
    tags: ["bow", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['charge'],
  },
  {
    id: 'lady_maria',
    name: 'Lady Maria',
    nameAr: 'الليدي ماريا',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'laurence',
    name: 'Laurence',
    nameAr: 'لورانس',
    finalImage: require('../../assets/cards/final/orc-warrior.png'), // TODO: missing image
    attack: 17, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'gehrman',
    name: 'Gehrman',
    nameAr: 'جيرمان',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'ludwig',
    name: 'Ludwig',
    nameAr: 'لودفيغ',
    finalImage: require('../../assets/cards/final/orc-warrior.png'), // TODO: missing image
    attack: 17, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'emlyn_white',
    name: 'Emlyn White',
    nameAr: 'إيميلين وايت',
    finalImage: require('../../assets/cards/final/human-knight.png'), // TODO: missing image
    attack: 8, defense: 7,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'ice',
  },
  {
    id: 'alger_wilson',
    name: 'Alger Wilson',
    nameAr: 'ألغر ويلسون',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 13, defense: 12,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'audrey_hall',
    name: 'Audrey Hall',
    nameAr: 'أودري هول',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 15, defense: 12,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'cattleya',
    name: 'Cattleya',
    nameAr: 'كاتليا',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'roselle_gustav',
    name: 'Roselle Gustav',
    nameAr: 'روزيل غوستاف',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'azik_eggers',
    name: 'Azik Eggers',
    nameAr: 'أزيك إيغرز',
    finalImage: require('../../assets/cards/final/human-knight.png'), // TODO: missing image
    attack: 16, defense: 16,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['taunt'],
  },
  {
    id: 'klein_moretti',
    name: 'Klein Moretti',
    nameAr: 'كلاين موريتي',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'feanor',
    name: 'Feanor',
    nameAr: 'فيانور',
    finalImage: require('../../assets/cards/final/elf-knight.png'), // TODO: missing image
    attack: 17, defense: 16,
    race: 'elf', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'amon',
    name: 'Amon',
    nameAr: 'أمون',
    finalImage: require('../../assets/cards/final/orc-warrior.png'), // TODO: missing image
    attack: 17, defense: 18,
    race: 'orc', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'rin_okumura',
    name: 'Rin Okumura',
    nameAr: 'رين أوكومورا',
    finalImage: require('../../assets/cards/final/demon-warrior.png'), // TODO: missing image
    attack: 15, defense: 11,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'amaimon',
    name: 'Amaimon',
    nameAr: 'عمايمون',
    finalImage: require('../../assets/cards/final/demon-warrior.png'), // TODO: missing image
    attack: 13, defense: 14,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'satan',
    name: 'Satan',
    nameAr: 'ساتان',
    finalImage: require('../../assets/cards/final/demon-warrior.png'), // TODO: missing image
    attack: 19, defense: 16,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'lilith',
    name: 'Lilith',
    nameAr: 'ليليث',
    finalImage: require('../../assets/cards/final/demon-warrior.png'), // TODO: missing image
    attack: 16, defense: 17,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'diablo',
    name: 'Diablo',
    nameAr: 'ديابلو',
    finalImage: require('../../assets/cards/final/demon-warrior.png'), // TODO: missing image
    attack: 19, defense: 16,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'lucifer',
    name: 'Lucifer',
    nameAr: 'لوسيفر',
    finalImage: require('../../assets/cards/final/demon-warrior.png'), // TODO: missing image
    attack: 18, defense: 16,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'power',
    name: 'Power',
    nameAr: 'باور',
    finalImage: require('../../assets/cards/final/demon-warrior.png'), // TODO: missing image
    attack: 12, defense: 12,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'denji',
    name: 'Denji',
    nameAr: 'دينجي',
    finalImage: require('../../assets/cards/final/demon-warrior.png'), // TODO: missing image
    attack: 15, defense: 11,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'makima',
    name: 'Makima',
    nameAr: 'ماكيما',
    finalImage: require('../../assets/cards/final/demon-warrior.png'), // TODO: missing image
    attack: 17, defense: 16,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'ram',
    name: 'Ram',
    nameAr: 'رام',
    finalImage: require('../../assets/cards/final/elf-knight.png'), // TODO: missing image
    attack: 8, defense: 8,
    race: 'elf', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'ice',
  },
  {
    id: 'rem',
    name: 'Rem',
    nameAr: 'ريم',
    finalImage: require('../../assets/cards/final/orc-warrior.png'), // TODO: missing image
    attack: 14, defense: 15,
    race: 'orc', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'emilia',
    name: 'Emilia',
    nameAr: 'إيميليا',
    finalImage: require('../../assets/cards/final/elf-knight.png'), // TODO: missing image
    attack: 11, defense: 11,
    race: 'elf', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'puck',
    name: 'Puck',
    nameAr: 'باك',
    finalImage: require('../../assets/cards/final/elf-knight.png'), // TODO: missing image
    attack: 12, defense: 12,
    race: 'elf', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'petelgeuse',
    name: 'Petelgeuse',
    nameAr: 'بيتلغيوز',
    finalImage: require('../../assets/cards/final/human-knight.png'), // TODO: missing image
    attack: 13, defense: 11,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'beatrice',
    name: 'Beatrice',
    nameAr: 'بياتريس',
    finalImage: require('../../assets/cards/final/elf-knight.png'), // TODO: missing image
    attack: 14, defense: 11,
    race: 'elf', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
];
