import { Card, Element, ElementAdvantage, Effect, ELEMENT_ADVANTAGES, ELEMENT_WEAKNESSES, ELEMENT_MULTIPLIER } from './types';

// Batch 6/6 — Cards 231 to 275
// Universes: Dark Souls, Overlord, The Witcher, Vinland Saga, Jujutsu Kaisen, Gurren Lagann, Neon Genesis, Mega Man, Berserk, Claymore, Hunter x Hunter, Attack on Titan, My Hero Academia

export const CARDS_BATCH_6: Card[] = [
  {
    id: 'sif_the_wolf',
    name: 'Sif the Wolf',
    nameAr: 'سيف الذئب',
    finalImage: require('../../assets/characters/epic/sif_the_wolf.png'),
    attack: 14, defense: 12,
    race: 'orc', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'smough',
    name: 'Smough',
    nameAr: 'سماو',
    finalImage: require('../../assets/characters/epic/smough.png'),
    attack: 15, defense: 11,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'ornstein',
    name: 'Ornstein',
    nameAr: 'أورنشتاين',
    finalImage: require('../../assets/characters/epic/ornstein.png'),
    attack: 15, defense: 12,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'gwyn',
    name: 'Gwyn',
    nameAr: 'غوين',
    finalImage: require('../../assets/characters/legendary/gwyn.png'),
    attack: 17, defense: 16,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['taunt'],
  },
  {
    id: 'artorias',
    name: 'Artorias',
    nameAr: 'أرتورياس',
    finalImage: require('../../assets/characters/legendary/artorias.png'),
    attack: 16, defense: 17,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['taunt'],
  },
  {
    id: 'lich_general',
    name: 'Lich (General)',
    nameAr: 'ليتش العام',
    finalImage: require('../../assets/characters/epic/lich_general.png'),
    attack: 15, defense: 13,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'pandoras_actor',
    name: 'Pandora\'s Actor',
    nameAr: 'ممثل باندورا',
    finalImage: require('../../assets/characters/epic/pandoras_actor.png'),
    attack: 15, defense: 11,
    race: 'human', cardClass: 'mage', element: 'ice',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'aura_bella_fiora',
    name: 'Aura Bella Fiora',
    nameAr: 'أورا بيلا فيورا',
    finalImage: require('../../assets/characters/epic/aura_bella_fiora.png'),
    attack: 14, defense: 13,
    race: 'elf', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'mare_bello_fiore',
    name: 'Mare Bello Fiore',
    nameAr: 'ماري بيلو فيوري',
    finalImage: require('../../assets/characters/epic/mare_bello_fiore.png'),
    attack: 14, defense: 11,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'albedo',
    name: 'Albedo',
    nameAr: 'ألبيدو',
    finalImage: require('../../assets/characters/epic/albedo.png'),
    attack: 15, defense: 12,
    race: 'orc', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'cocytus',
    name: 'Cocytus',
    nameAr: 'كوسيتوس',
    finalImage: require('../../assets/characters/epic/cocytus.png'),
    attack: 13, defense: 12,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'shalltear',
    name: 'Shalltear',
    nameAr: 'شالتير',
    finalImage: require('../../assets/characters/epic/shalltear.png'),
    attack: 14, defense: 15,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'ainz_ooal_gown',
    name: 'Ainz Ooal Gown',
    nameAr: 'آينز أوال غاون',
    finalImage: require('../../assets/characters/legendary/ainz_ooal_gown.png'),
    attack: 17, defense: 16,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['taunt'],
  },
  {
    id: 'caretaker',
    name: 'Caretaker',
    nameAr: 'الحارس',
    finalImage: require('../../assets/characters/epic/caretaker.png'),
    attack: 12, defense: 12,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'regis',
    name: 'Regis',
    nameAr: 'ريجيس',
    finalImage: require('../../assets/characters/epic/regis.png'),
    attack: 15, defense: 12,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'dettlaff',
    name: 'Dettlaff',
    nameAr: 'ديتلاف',
    finalImage: require('../../assets/characters/epic/dettlaff.png'),
    attack: 15, defense: 11,
    race: 'orc', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'gaunter_o_dimm',
    name: 'Gaunter O Dimm',
    nameAr: 'غونتر أو ديم',
    finalImage: require('../../assets/characters/legendary/gaunter_o_dimm.png'),
    attack: 17, defense: 16,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['taunt'],
  },
  {
    id: 'floki',
    name: 'Floki',
    nameAr: 'فلوكي',
    finalImage: require('../../assets/characters/rare/floki.png'),
    attack: 9, defense: 8,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'ice',
  },
  {
    id: 'askeladd',
    name: 'Askeladd',
    nameAr: 'أسكيلاد',
    finalImage: require('../../assets/characters/epic/askeladd.png'),
    attack: 13, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'thorfinn',
    name: 'Thorfinn',
    nameAr: 'ثورفين',
    finalImage: require('../../assets/characters/epic/thorfinn.png'),
    attack: 12, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'thorkell',
    name: 'Thorkell',
    nameAr: 'ثوركيل',
    finalImage: require('../../assets/characters/epic/thorkell.png'),
    attack: 13, defense: 14,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'yuta_okkotsu',
    name: 'Yuta Okkotsu',
    nameAr: 'يوتا أوكوتسو',
    finalImage: require('../../assets/characters/epic/yuta_okkotsu.png'),
    attack: 15, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'nia_teppelin',
    name: 'Nia Teppelin',
    nameAr: 'نيا تيبلين',
    finalImage: require('../../assets/characters/rare/nia_teppelin.png'),
    attack: 9, defense: 8,
    race: 'human', cardClass: 'mage', element: 'earth',
    tags: ["magic"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'kamina',
    name: 'Kamina',
    nameAr: 'كامينا',
    finalImage: require('../../assets/characters/epic/kamina.png'),
    attack: 12, defense: 11,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'viral',
    name: 'Viral',
    nameAr: 'فايرال',
    finalImage: require('../../assets/characters/epic/viral.png'),
    attack: 15, defense: 12,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'lordgenome',
    name: 'Lordgenome',
    nameAr: 'لورد غينوم',
    finalImage: require('../../assets/characters/epic/lordgenome.png'),
    attack: 14, defense: 13,
    race: 'human', cardClass: 'knight', element: 'lightning',
    tags: ["sword", "shield"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
    cardEffects: ['divine_shield'],
  },
  {
    id: 'shinji_ikari',
    name: 'Shinji Ikari',
    nameAr: 'شينجي إيكاري',
    finalImage: require('../../assets/characters/epic/shinji_ikari.png'),
    attack: 14, defense: 13,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'asuka_langley',
    name: 'Asuka Langley',
    nameAr: 'أسوكا لانغلي',
    finalImage: require('../../assets/characters/epic/asuka_langley.png'),
    attack: 13, defense: 11,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'rei_ayanami',
    name: 'Rei Ayanami',
    nameAr: 'ري أيانامي',
    finalImage: require('../../assets/characters/epic/rei_ayanami.png'),
    attack: 13, defense: 14,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'kaworu_nagisa',
    name: 'Kaworu Nagisa',
    nameAr: 'كاورو ناغيسا',
    finalImage: require('../../assets/characters/epic/kaworu_nagisa.png'),
    attack: 14, defense: 13,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'unit_01',
    name: 'Unit-01',
    nameAr: 'الوحدة 01',
    finalImage: require('../../assets/characters/legendary/unit_01.png'),
    attack: 16, defense: 16,
    race: 'human', cardClass: 'mage', element: 'ice',
    tags: ["magic", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'dr_cossack',
    name: 'Dr. Cossack',
    nameAr: 'د. كوساك',
    finalImage: require('../../assets/characters/rare/dr_cossack.png'),
    attack: 6, defense: 6,
    race: 'human', cardClass: 'mage', element: 'earth',
    tags: ["magic"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'mega_man',
    name: 'Mega Man',
    nameAr: 'ميغا مان',
    finalImage: require('../../assets/characters/epic/mega_man.png'),
    attack: 13, defense: 12,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'bass',
    name: 'Bass',
    nameAr: 'باس',
    finalImage: require('../../assets/characters/epic/bass.png'),
    attack: 15, defense: 11,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'zero',
    name: 'Zero',
    nameAr: 'زيرو',
    finalImage: require('../../assets/characters/epic/zero.png'),
    attack: 15, defense: 12,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'sigma',
    name: 'Sigma',
    nameAr: 'سيغما',
    finalImage: require('../../assets/characters/epic/sigma.png'),
    attack: 14, defense: 14,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'zodd',
    name: 'Zodd',
    nameAr: 'زود',
    finalImage: require('../../assets/characters/epic/zodd.png'),
    attack: 15, defense: 12,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'griffith_dragon',
    name: 'Griffith Dragon',
    nameAr: 'غريفث التنين',
    finalImage: require('../../assets/characters/legendary/griffith_dragon.png'),
    attack: 16, defense: 16,
    race: 'dragon', cardClass: 'warrior', element: 'earth',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'guts',
    name: 'Guts',
    nameAr: 'غاتس',
    finalImage: require('../../assets/characters/legendary/guts.png'),
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'griffith',
    name: 'Griffith',
    nameAr: 'غريفث',
    finalImage: require('../../assets/characters/legendary/griffith.png'),
    attack: 16, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'clare',
    name: 'Clare',
    nameAr: 'كلير',
    finalImage: require('../../assets/characters/epic/clare.png'),
    attack: 13, defense: 11,
    race: 'orc', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'teresa',
    name: 'Teresa',
    nameAr: 'تيريزا',
    finalImage: require('../../assets/characters/legendary/teresa.png'),
    attack: 17, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'neferpitou',
    name: 'Neferpitou',
    nameAr: 'نيفيربيتو',
    finalImage: require('../../assets/characters/epic/neferpitou.png'),
    attack: 15, defense: 11,
    race: 'orc', cardClass: 'warrior', element: 'wind',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'colossal_titan',
    name: 'Colossal Titan',
    nameAr: 'التيتان العملاق',
    finalImage: require('../../assets/characters/epic/colossal_titan.png'),
    attack: 15, defense: 12,
    race: 'orc', cardClass: 'berserker', element: 'earth',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
    cardEffects: ['charge'],
  },
  {
    id: 'mineta',
    name: 'Mineta',
    nameAr: 'مينيتا',
    finalImage: require('../../assets/characters/common/mineta.png'),
    attack: 3, defense: 2,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'common', stars: 2,
    animationPreset: 'lightning',
  },
];
