import { Card, Element, ElementAdvantage, Effect, ELEMENT_ADVANTAGES, ELEMENT_WEAKNESSES, ELEMENT_MULTIPLIER } from './types';

// Batch 2/6 — Dragon Ball, AoT, Death Note, Demon Slayer

export const CARDS_BATCH_2: Card[] = [
  {
    id: 'yamcha',
    name: 'Yamcha',
    nameAr: 'يامتشا',
    attack: 6, defense: 6,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'fire',
  },
  {
    id: 'tien_shinhan',
    name: 'Tien Shinhan',
    nameAr: 'تيان شينهان',
    attack: 8, defense: 9,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'fire',
  },
  {
    id: 'krillin',
    name: 'Krillin',
    nameAr: 'كريلين',
    attack: 15, defense: 13,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'master_roshi',
    name: 'Master Roshi',
    nameAr: 'الماستر روشي',
    attack: 12, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'piccolo',
    name: 'Piccolo',
    nameAr: 'بيكولو',
    attack: 18, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'syn_shenron',
    name: 'Syn Shenron',
    nameAr: 'سين شينرون',
    attack: 18, defense: 16,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'trunks',
    name: 'Trunks',
    nameAr: 'ترانكس',
    attack: 17, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'gohan',
    name: 'Gohan',
    nameAr: 'غوهان',
    attack: 16, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'cell',
    name: 'Cell',
    nameAr: 'سيل',
    attack: 17, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'frieza',
    name: 'Frieza',
    nameAr: 'فريزا',
    attack: 17, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'vegeta',
    name: 'Vegeta',
    nameAr: 'فيجيتا',
    attack: 17, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'broly',
    name: 'Broly',
    nameAr: 'بروللي',
    attack: 18, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'omega_shenron',
    name: 'Omega Shenron',
    nameAr: 'أوميغا شينرون',
    attack: 19, defense: 16,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'son_goku',
    name: 'Son Goku',
    nameAr: 'غوكو',
    attack: 18, defense: 17,
    race: 'orc', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'hitch_dreyse',
    name: 'Hitch Dreyse',
    nameAr: 'هيتش دريس',
    attack: 1, defense: 1,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'common', stars: 1,
    animationPreset: 'default',
  },
  {
    id: 'sasha_braus',
    name: 'Sasha Braus',
    nameAr: 'ساشا براوس',
    attack: 8, defense: 6,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'falco_grice',
    name: 'Falco Grice',
    nameAr: 'فالكو غرايس',
    attack: 9, defense: 7,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'armin_arlert',
    name: 'Armin Arlert',
    nameAr: 'أرمين أرليرت',
    attack: 13, defense: 11,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'bertholdt_hoover',
    name: 'Bertholdt Hoover',
    nameAr: 'بيرتولدت هوفر',
    attack: 12, defense: 12,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'porco_galliard',
    name: 'Porco Galliard',
    nameAr: 'بوركو غاليارد',
    attack: 14, defense: 11,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'annie_leonhart',
    name: 'Annie Leonhart',
    nameAr: 'آني ليونهارت',
    attack: 14, defense: 11,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'mikasa_ackerman',
    name: 'Mikasa Ackerman',
    nameAr: 'ميكاسا أكرمان',
    attack: 15, defense: 14,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'reiner_braun',
    name: 'Reiner Braun',
    nameAr: 'راينر براون',
    attack: 16, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'zeke_yeager',
    name: 'Zeke Yeager',
    nameAr: 'زيك ييغر',
    attack: 16, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'eren_yeager',
    name: 'Eren Yeager',
    nameAr: 'إيرين ييغر',
    attack: 16, defense: 17,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'levi_ackerman',
    name: 'Levi Ackerman',
    nameAr: 'ليفي أكرمان',
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'misa_amane',
    name: 'Misa Amane',
    nameAr: 'ميسا أماني',
    attack: 1, defense: 2,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'common', stars: 1,
    animationPreset: 'ice',
  },
  {
    id: 'l_lawliet',
    name: 'L (Lawliet)',
    nameAr: 'إل',
    attack: 6, defense: 6,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'ice',
  },
  {
    id: 'light_yagami',
    name: 'Light Yagami',
    nameAr: 'لايت ياغامي',
    attack: 8, defense: 6,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'ice',
  },
  {
    id: 'ryuk',
    name: 'Ryuk',
    nameAr: 'ريوك',
    attack: 17, defense: 16,
    race: 'demon', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['poison'],
  },
  {
    id: 'inosuke_hashibira',
    name: 'Inosuke Hashibira',
    nameAr: 'إينوسوكي هاشيبيرا',
    attack: 13, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'zenitsu_agatsuma',
    name: 'Zenitsu Agatsuma',
    nameAr: 'زينيتسو أغاتسوما',
    attack: 13, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'nezuko_kamado',
    name: 'Nezuko Kamado',
    nameAr: 'نيزوكو كامادو',
    attack: 13, defense: 11,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'shinobu_kocho',
    name: 'Shinobu Kocho',
    nameAr: 'شينوبو كوتشو',
    attack: 12, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'tanjiro_kamado',
    name: 'Tanjiro Kamado',
    nameAr: 'تانجيرو كامادو',
    attack: 15, defense: 12,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'mitsuri_kanroji',
    name: 'Mitsuri Kanroji',
    nameAr: 'ميتسوري كانروجي',
    attack: 13, defense: 14,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'gyutaro',
    name: 'Gyutaro',
    nameAr: 'غيوتارو',
    attack: 14, defense: 13,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
];
