import { Card, Element, ElementAdvantage, Effect, ELEMENT_ADVANTAGES, ELEMENT_WEAKNESSES, ELEMENT_MULTIPLIER } from './types';

// Batch 5/6 — Cards 185 to 230
// Universes: Re:Zero, The Legend of Zelda, Sword Art Online, Log Horizon, The Elder Scrolls, Fairy Tail, Monster Hunter, Castlevania

export const CARDS_BATCH_5: Card[] = [
  {
    id: 'satella',
    name: 'Satella',
    nameAr: 'ساتيلا',
    attack: 19, defense: 16,
    race: 'elf', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'ganondorf',
    name: 'Ganondorf',
    nameAr: 'غانوندورف',
    attack: 16, defense: 17,
    race: 'elf', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'silica',
    name: 'Silica',
    nameAr: 'سيليكا',
    attack: 9, defense: 9,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'yui',
    name: 'Yui',
    nameAr: 'يوي',
    attack: 7, defense: 6,
    race: 'human', cardClass: 'mage', element: 'earth',
    tags: ["magic"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'eugeo',
    name: 'Eugeo',
    nameAr: 'يوجيو',
    attack: 13, defense: 12,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'heathcliff_kayaba',
    name: 'Heathcliff (Kayaba)',
    nameAr: 'هيثكليف (كايابا)',
    attack: 13, defense: 13,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'alice_zuberg',
    name: 'Alice Zuberg',
    nameAr: 'أليس زيوبيرغ',
    attack: 13, defense: 13,
    race: 'elf', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'rundelhaus',
    name: 'Rundelhaus',
    nameAr: 'روندلهاوس',
    attack: 8, defense: 8,
    race: 'elf', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'nyanta',
    name: 'Nyanta',
    nameAr: 'نيانتا',
    attack: 11, defense: 12,
    race: 'elf', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'paarthurnax',
    name: 'Paarthurnax',
    nameAr: 'بارثورناكس',
    attack: 16, defense: 17,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'alduin',
    name: 'Alduin',
    nameAr: 'ألدوين',
    attack: 17, defense: 16,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'happy',
    name: 'Happy',
    nameAr: 'هابي',
    attack: 4, defense: 2,
    race: 'orc', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'common', stars: 2,
    animationPreset: 'fire',
  },
  {
    id: 'igneel',
    name: 'Igneel',
    nameAr: 'إيغنيل',
    attack: 16, defense: 17,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'mavis_vermillion',
    name: 'Mavis Vermillion',
    nameAr: 'ماڤيس فيرميليون',
    attack: 17, defense: 16,
    race: 'elf', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'acnologia',
    name: 'Acnologia',
    nameAr: 'أكنولوجيا',
    attack: 16, defense: 16,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'zeref_dragneel',
    name: 'Zeref Dragneel',
    nameAr: 'زيريف دراغنيل',
    attack: 16, defense: 17,
    race: 'elf', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'fatalis',
    name: 'Fatalis',
    nameAr: 'فاتاليس',
    attack: 18, defense: 16,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'hector',
    name: 'Hector',
    nameAr: 'هيكتور',
    attack: 14, defense: 11,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'isaac',
    name: 'Isaac',
    nameAr: 'إسحاق',
    attack: 15, defense: 11,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'alucard',
    name: 'Alucard',
    nameAr: 'ألوكارد',
    attack: 18, defense: 16,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['taunt'],
  },
  {
    id: 'death',
    name: 'Death',
    nameAr: 'الموت',
    attack: 18, defense: 16,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['taunt'],
  },
  {
    id: 'dracula',
    name: 'Dracula',
    nameAr: 'دراكولا',
    attack: 18, defense: 16,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['taunt'],
  },
];
