import { Card, Element, ElementAdvantage, Effect, ELEMENT_ADVANTAGES, ELEMENT_WEAKNESSES, ELEMENT_MULTIPLIER } from './types';

// Batch 1/6 — Cards 1 to 46
// Universes: One Piece, Naruto, Dragon Ball

export const CARDS_BATCH_1: Card[] = [
  {
    id: 'yosaku',
    name: 'Yosaku',
    nameAr: 'يوساكو',
    finalImage: require('../../assets/characters/common/yosaku.png'),
    attack: 2, defense: 1,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'common', stars: 1,
    animationPreset: 'default',
  },
  {
    id: 'johnny',
    name: 'Johnny',
    nameAr: 'جوني',
    finalImage: require('../../assets/characters/common/johnny.png'),
    attack: 3, defense: 0,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'common', stars: 1,
    animationPreset: 'default',
  },
  {
    id: 'nami',
    name: 'Nami',
    nameAr: 'نامي',
    finalImage: require('../../assets/characters/common/nami.png'),
    attack: 3, defense: 2,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'common', stars: 1,
    animationPreset: 'default',
  },
  {
    id: 'coby',
    name: 'Coby',
    nameAr: 'كوبي',
    finalImage: require('../../assets/characters/rare/coby.png'),
    attack: 6, defense: 6,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'usopp',
    name: 'Usopp',
    nameAr: 'أوسوب',
    finalImage: require('../../assets/characters/rare/usopp.png'),
    attack: 8, defense: 6,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'tony_tony_chopper',
    name: 'Tony Tony Chopper',
    nameAr: 'توني توني تشوبر',
    finalImage: require('../../assets/characters/rare/tony_tony_chopper.png'),
    attack: 9, defense: 6,
    race: 'orc', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'nico_robin',
    name: 'Nico Robin',
    nameAr: 'نيكو روبين',
    finalImage: require('../../assets/characters/epic/nico_robin.png'),
    attack: 12, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'brook',
    name: 'Brook',
    nameAr: 'بروك',
    finalImage: require('../../assets/characters/epic/brook.png'),
    attack: 11, defense: 11,
    race: 'undead', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'franky',
    name: 'Franky',
    nameAr: 'فرانكي',
    finalImage: require('../../assets/characters/epic/franky.png'),
    attack: 13, defense: 11,
    race: 'human', cardClass: 'mage', element: 'water',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'eustass_kid',
    name: 'Eustass Kid',
    nameAr: 'يوستاس كيد',
    finalImage: require('../../assets/characters/epic/eustass_kid.png'),
    attack: 13, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'crocodile',
    name: 'Crocodile',
    nameAr: 'كروكودايل',
    finalImage: require('../../assets/characters/epic/crocodile.png'),
    attack: 14, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'donquixote_doflamingo',
    name: 'Donquixote Doflamingo',
    nameAr: 'دوفلامينغو',
    finalImage: require('../../assets/characters/epic/donquixote_doflamingo.png'),
    attack: 13, defense: 14,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'white_snake',
    name: 'White Snake',
    nameAr: 'الحية البيضاء',
    finalImage: require('../../assets/characters/epic/white_snake.png'),
    attack: 15, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'boa_hancock',
    name: 'Boa Hancock',
    nameAr: 'بوا هانكوك',
    finalImage: require('../../assets/characters/epic/boa_hancock.png'),
    attack: 13, defense: 14,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'black_maria',
    name: 'Black Maria',
    nameAr: 'الحية السوداء',
    finalImage: require('../../assets/characters/epic/black_maria.png'),
    attack: 13, defense: 12,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'trafalgar_law',
    name: 'Trafalgar Law',
    nameAr: 'ترافلغار لاو',
    finalImage: require('../../assets/characters/epic/trafalgar_law.png'),
    attack: 14, defense: 15,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'jinbe',
    name: 'Jinbe',
    nameAr: 'جينبي',
    finalImage: require('../../assets/characters/legendary/jinbe.png'),
    attack: 16, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'sabo',
    name: 'Sabo',
    nameAr: 'سابو',
    finalImage: require('../../assets/characters/legendary/sabo.png'),
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'sanji',
    name: 'Sanji',
    nameAr: 'سانجي',
    finalImage: require('../../assets/characters/legendary/sanji.png'),
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'shiki',
    name: 'Shiki',
    nameAr: 'شيكي',
    finalImage: require('../../assets/characters/legendary/shiki.png'),
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'roronoa_zoro',
    name: 'Roronoa Zoro',
    nameAr: 'رورونوا زورو',
    finalImage: require('../../assets/characters/legendary/roronoa_zoro.png'),
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'dracule_mihawk',
    name: 'Dracule Mihawk',
    nameAr: 'دراكيول ميهوك',
    finalImage: require('../../assets/characters/legendary/dracule_mihawk.png'),
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'monkey_d_luffy',
    name: 'Monkey D. Luffy',
    nameAr: 'مونكي دي لوفي',
    finalImage: require('../../assets/characters/legendary/monkey_d_luffy.png'),
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'gol_d_roger',
    name: 'Gol D. Roger',
    nameAr: 'غول دي روجر',
    finalImage: require('../../assets/characters/legendary/gol_d_roger.png'),
    attack: 17, defense: 18,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'kaido',
    name: 'Kaido',
    nameAr: 'كايدو',
    finalImage: require('../../assets/characters/legendary/kaido.png'),
    attack: 19, defense: 16,
    race: 'dragon', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'ebisu',
    name: 'Ebisu',
    nameAr: 'إيبيسو',
    finalImage: require('../../assets/characters/common/ebisu.png'),
    attack: 3, defense: 0,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword"],
    rarity: 'common', stars: 1,
    animationPreset: 'default',
  },
  {
    id: 'konohamaru',
    name: 'Konohamaru',
    nameAr: 'كونوهامارو',
    finalImage: require('../../assets/characters/common/konohamaru.png'),
    attack: 5, defense: 0,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword"],
    rarity: 'common', stars: 2,
    animationPreset: 'default',
  },
  {
    id: 'sakura_haruno',
    name: 'Sakura Haruno',
    nameAr: 'ساكورا هارونو',
    finalImage: require('../../assets/characters/epic/sakura_haruno.png'),
    attack: 12, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'neji_hyuga',
    name: 'Neji Hyuga',
    nameAr: 'نيجي هيوغا',
    finalImage: require('../../assets/characters/epic/neji_hyuga.png'),
    attack: 14, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'rock_lee',
    name: 'Rock Lee',
    nameAr: 'روك لي',
    finalImage: require('../../assets/characters/epic/rock_lee.png'),
    attack: 13, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'killer_bee',
    name: 'Killer Bee',
    nameAr: 'كيلر بي',
    finalImage: require('../../assets/characters/epic/killer_bee.png'),
    attack: 13, defense: 12,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'gaara',
    name: 'Gaara',
    nameAr: 'غارا',
    finalImage: require('../../assets/characters/epic/gaara.png'),
    attack: 14, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'tsunade',
    name: 'Tsunade',
    nameAr: 'تسونادي',
    finalImage: require('../../assets/characters/epic/tsunade.png'),
    attack: 13, defense: 13,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'orochimaru',
    name: 'Orochimaru',
    nameAr: 'أوروتشيمارو',
    finalImage: require('../../assets/characters/epic/orochimaru.png'),
    attack: 15, defense: 13,
    race: 'orc', cardClass: 'warrior', element: 'wind',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'kakashi_hatake',
    name: 'Kakashi Hatake',
    nameAr: 'كاكاشي هاتاكي',
    finalImage: require('../../assets/characters/legendary/kakashi_hatake.png'),
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'jiraiya',
    name: 'Jiraiya',
    nameAr: 'جيرايا',
    finalImage: require('../../assets/characters/legendary/jiraiya.png'),
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'might_guy',
    name: 'Might Guy',
    nameAr: 'مايت غاي',
    finalImage: require('../../assets/characters/legendary/might_guy.png'),
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'obito_uchiha',
    name: 'Obito Uchiha',
    nameAr: 'أوبيتو أوتشيها',
    finalImage: require('../../assets/characters/legendary/obito_uchiha.png'),
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'itachi_uchiha',
    name: 'Itachi Uchiha',
    nameAr: 'إيتاتشي أوتشيها',
    finalImage: require('../../assets/characters/legendary/itachi_uchiha.png'),
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'pain_nagato',
    name: 'Pain (Nagato)',
    nameAr: 'باين (ناغاتو)',
    finalImage: require('../../assets/characters/legendary/pain_nagato.png'),
    attack: 16, defense: 17,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'minato_namikaze',
    name: 'Minato Namikaze',
    nameAr: 'ميناتو ناميكازي',
    finalImage: require('../../assets/characters/legendary/minato_namikaze.png'),
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'sasuke_uchiha',
    name: 'Sasuke Uchiha',
    nameAr: 'ساسكي أوتشيها',
    finalImage: require('../../assets/characters/legendary/sasuke_uchiha.png'),
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'naruto_uzumaki',
    name: 'Naruto Uzumaki',
    nameAr: 'ناروتو أوزوماكي',
    finalImage: require('../../assets/characters/legendary/naruto_uzumaki.png'),
    attack: 19, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'madara_uchiha',
    name: 'Madara Uchiha',
    nameAr: 'مادارا أوتشيها',
    finalImage: require('../../assets/characters/legendary/madara_uchiha.png'),
    attack: 17, defense: 17,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'bulma',
    name: 'Bulma',
    nameAr: 'بولما',
    finalImage: require('../../assets/characters/common/bulma.png'),
    attack: 1, defense: 0,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'common', stars: 1,
    animationPreset: 'fire',
  },
  {
    id: 'dende',
    name: 'Dende',
    nameAr: 'ديندي',
    finalImage: require('../../assets/characters/rare/dende.png'),
    attack: 6, defense: 6,
    race: 'elf', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'fire',
  },
];
