import { Card, Element, ElementAdvantage, Effect, ELEMENT_ADVANTAGES, ELEMENT_WEAKNESSES, ELEMENT_MULTIPLIER } from './types';

// Batch 1/6 — Cards 1 to 46
// Universes: One Piece, Naruto, Dragon Ball

export const CARDS_BATCH_1: Card[] = [
  {
    id: 'yosaku',
    name: 'Yosaku',
    nameAr: 'يوساكو',
    finalImage: require('../../assets/characters/common/yosaku.png'),
    attack: 2, defense: 1,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'common', stars: 1,
    animationPreset: 'default',
  },
  {
    id: 'johnny',
    name: 'Johnny',
    nameAr: 'جوني',
    finalImage: require('../../assets/cards/final/human-warrior.png'),  // TODO: missing image
    attack: 3, defense: 0,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'common', stars: 1,
    animationPreset: 'default',
  },
  {
    id: 'nami',
    name: 'Nami',
    nameAr: 'نامي',
    finalImage: require('../../assets/characters/common/nami.png'),
    attack: 3, defense: 2,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'common', stars: 1,
    animationPreset: 'default',
  },
  {
    id: 'coby',
    name: 'Coby',
    nameAr: 'كوبي',
    finalImage: require('../../assets/characters/rare/coby.png'),
    attack: 6, defense: 6,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'usopp',
    name: 'Usopp',
    nameAr: 'أوسوب',
    finalImage: require('../../assets/characters/rare/usopp.png'),
    attack: 8, defense: 6,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'tony_tony_chopper',
    name: 'Tony Tony Chopper',
    nameAr: 'توني توني تشوبر',
    finalImage: require('../../assets/characters/rare/tony_tony_chopper.png'),
    attack: 9, defense: 6,
    race: 'orc', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'nico_robin',
    name: 'Nico Robin',
    nameAr: 'نيكو روبين',
    finalImage: require('../../assets/characters/epic/nico_robin.png'),
    attack: 12, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'brook',
    name: 'Brook',
    nameAr: 'بروك',
    finalImage: require('../../assets/characters/epic/brook.png'),
    attack: 11, defense: 11,
    race: 'undead', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'franky',
    name: 'Franky',
    nameAr: 'فرانكي',
    finalImage: require('../../assets/characters/epic/franky.png'),
    attack: 13, defense: 11,
    race: 'human', cardClass: 'mage', element: 'water',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'eustass_kid',
    name: 'Eustass Kid',
    nameAr: 'يوستاس كيد',
    finalImage: require('../../assets/characters/epic/eustass_kid.png'),
    attack: 13, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'crocodile',
    name: 'Crocodile',
    nameAr: 'كروكودايل',
    finalImage: require('../../assets/characters/epic/crocodile.png'),
    attack: 14, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'donquixote_doflamingo',
    name: 'Donquixote Doflamingo',
    nameAr: 'دوفلامينغو',
    finalImage: require('../../assets/characters/epic/donquixote_doflamingo.png'),
    attack: 13, defense: 14,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'white_snake',
    name: 'White Snake',
    nameAr: 'الحية البيضاء',
    finalImage: require('../../assets/characters/epic/white_snake.png'),
    attack: 15, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'boa_hancock',
    name: 'Boa Hancock',
    nameAr: 'بوا هانكوك',
    finalImage: require('../../assets/characters/epic/boa_hancock.png'),
    attack: 13, defense: 14,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'black_maria',
    name: 'Black Maria',
    nameAr: 'الحية السوداء',
    finalImage: require('../../assets/characters/epic/black_maria.png'),
    attack: 13, defense: 12,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'trafalgar_law',
    name: 'Trafalgar Law',
    nameAr: 'ترافلغار لاو',
    finalImage: require('../../assets/characters/epic/trafalgar_law.png'),
    attack: 14, defense: 15,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'jinbe',
    name: 'Jinbe',
    nameAr: 'جينبي',
    finalImage: require('../../assets/characters/legendary/jinbe.png'),
    attack: 16, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'sabo',
    name: 'Sabo',
    nameAr: 'سابو',
    finalImage: require('../../assets/characters/legendary/sabo.png'),
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'sanji',
    name: 'Sanji',
    nameAr: 'سانجي',
    finalImage: require('../../assets/characters/legendary/sanji.png'),
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'shiki',
    name: 'Shiki',
    nameAr: 'شيكي',
    finalImage: require('../../assets/characters/legendary/shiki.png'),
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'roronoa_zoro',
    name: 'Roronoa Zoro',
    nameAr: 'رورونوا زورو',
    finalImage: require('../../assets/characters/legendary/roronoa_zoro.png'),
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'dracule_mihawk',
    name: 'Dracule Mihawk',
    nameAr: 'دراكيول ميهوك',
    finalImage: require('../../assets/characters/legendary/dracule_mihawk.png'),
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'monkey_d_luffy',
    name: 'Monkey D. Luffy',
    nameAr: 'مونكي دي لوفي',
    finalImage: require('../../assets/characters/legendary/monkey_d_luffy.png'),
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'gol_d_roger',
    name: 'Gol D. Roger',
    nameAr: 'غول دي روجر',
    finalImage: require('../../assets/characters/legendary/gol_d_roger.png'),
    attack: 17, defense: 18,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'kaido',
    name: 'Kaido',
    nameAr: 'كايدو',
    finalImage: require('../../assets/characters/legendary/kaido.png'),
    attack: 19, defense: 16,
    race: 'dragon', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'ebisu',
    name: 'Ebisu',
    nameAr: 'إيبيسو',
    finalImage: require('../../assets/characters/common/ebisu.png'),
    attack: 3, defense: 0,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword"],
    rarity: 'common', stars: 1,
    animationPreset: 'default',
  },
  {
    id: 'konohamaru',
    name: 'Konohamaru',
    nameAr: 'كونوهامارو',
    finalImage: require('../../assets/characters/common/konohamaru.png'),
    attack: 5, defense: 0,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword"],
    rarity: 'common', stars: 2,
    animationPreset: 'default',
  },
  {
    id: 'sakura_haruno',
    name: 'Sakura Haruno',
    nameAr: 'ساكورا هارونو',
    finalImage: require('../../assets/characters/epic/sakura_haruno.png'),
    attack: 12, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'neji_hyuga',
    name: 'Neji Hyuga',
    nameAr: 'نيجي هيوغا',
    finalImage: require('../../assets/characters/epic/neji_hyuga.png'),
    attack: 14, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'rock_lee',
    name: 'Rock Lee',
    nameAr: 'روك لي',
    finalImage: require('../../assets/characters/epic/rock_lee.png'),
    attack: 13, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'killer_bee',
    name: 'Killer Bee',
    nameAr: 'كيلر بي',
    finalImage: require('../../assets/characters/epic/killer_bee.png'),
    attack: 13, defense: 12,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'gaara',
    name: 'Gaara',
    nameAr: 'غارا',
    finalImage: require('../../assets/characters/epic/gaara.png'),
    attack: 14, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'tsunade',
    name: 'Tsunade',
    nameAr: 'تسونادي',
    finalImage: require('../../assets/characters/epic/tsunade.png'),
    attack: 13, defense: 13,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'orochimaru',
    name: 'Orochimaru',
    nameAr: 'أوروتشيمارو',
    finalImage: require('../../assets/characters/epic/orochimaru.png'),
    attack: 15, defense: 13,
    race: 'orc', cardClass: 'warrior', element: 'wind',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'kakashi_hatake',
    name: 'Kakashi Hatake',
    nameAr: 'كاكاشي هاتاكي',
    finalImage: require('../../assets/characters/legendary/kakashi_hatake.png'),
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'jiraiya',
    name: 'Jiraiya',
    nameAr: 'جيرايا',
    finalImage: require('../../assets/characters/legendary/jiraiya.png'),
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'might_guy',
    name: 'Might Guy',
    nameAr: 'مايت غاي',
    finalImage: require('../../assets/characters/legendary/might_guy.png'),
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'obito_uchiha',
    name: 'Obito Uchiha',
    nameAr: 'أوبيتو أوتشيها',
    finalImage: require('../../assets/characters/legendary/obito_uchiha.png'),
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'itachi_uchiha',
    name: 'Itachi Uchiha',
    nameAr: 'إيتاتشي أوتشيها',
    finalImage: require('../../assets/characters/legendary/itachi_uchiha.png'),
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'pain_nagato',
    name: 'Pain (Nagato)',
    nameAr: 'باين (ناغاتو)',
    finalImage: require('../../assets/characters/legendary/pain_nagato.png'),
    attack: 16, defense: 17,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'minato_namikaze',
    name: 'Minato Namikaze',
    nameAr: 'ميناتو ناميكازي',
    finalImage: require('../../assets/characters/legendary/minato_namikaze.png'),
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'sasuke_uchiha',
    name: 'Sasuke Uchiha',
    nameAr: 'ساسكي أوتشيها',
    finalImage: require('../../assets/characters/legendary/sasuke_uchiha.png'),
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'naruto_uzumaki',
    name: 'Naruto Uzumaki',
    nameAr: 'ناروتو أوزوماكي',
    finalImage: require('../../assets/characters/legendary/naruto_uzumaki.png'),
    attack: 19, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'madara_uchiha',
    name: 'Madara Uchiha',
    nameAr: 'مادارا أوتشيها',
    finalImage: require('../../assets/characters/legendary/madara_uchiha.png'),
    attack: 17, defense: 17,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'bulma',
    name: 'Bulma',
    nameAr: 'بولما',
    finalImage: require('../../assets/characters/common/bulma.png'),
    attack: 1, defense: 0,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'common', stars: 1,
    animationPreset: 'fire',
  },
  {
    id: 'dende',
    name: 'Dende',
    nameAr: 'ديندي',
    finalImage: require('../../assets/characters/rare/dende.png'),
    attack: 6, defense: 6,
    race: 'elf', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'fire',
  },
  {
    id: 'yamcha',
    name: 'Yamcha',
    nameAr: 'يامتشا',
    finalImage: require('../../assets/characters/rare/yamcha.png'),
    attack: 6, defense: 6,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'fire',
  },
  {
    id: 'tien_shinhan',
    name: 'Tien Shinhan',
    nameAr: 'تيان شينهان',
    finalImage: require('../../assets/characters/rare/tien_shinhan.png'),
    attack: 8, defense: 9,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'fire',
  },
  {
    id: 'krillin',
    name: 'Krillin',
    nameAr: 'كريلين',
    finalImage: require('../../assets/characters/epic/krillin.png'),
    attack: 15, defense: 13,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'nail',
    name: 'Nail',
    nameAr: 'نيل',
    finalImage: require('../../assets/characters/epic/nail.png'),
    attack: 14, defense: 14,
    race: 'elf', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'master_roshi',
    name: 'Master Roshi',
    nameAr: 'الماستر روشي',
    finalImage: require('../../assets/characters/epic/master_roshi.png'),
    attack: 12, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'lord_slug',
    name: 'Lord Slug',
    nameAr: 'اللورد سلوغ',
    finalImage: require('../../assets/characters/epic/lord_slug.png'),
    attack: 14, defense: 11,
    race: 'elf', cardClass: 'knight', element: 'fire',
    tags: ["sword", "shield"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
    cardEffects: ['divine_shield'],
  },
  {
    id: 'rage_shenron',
    name: 'Rage Shenron',
    nameAr: 'راج شينرون',
    finalImage: require('../../assets/characters/epic/rage_shenron.png'),
    attack: 14, defense: 11,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'nuova_shenron',
    name: 'Nuova Shenron',
    nameAr: 'نوفا شينرون',
    finalImage: require('../../assets/characters/epic/nuova_shenron.png'),
    attack: 13, defense: 14,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'porunga',
    name: 'Porunga',
    nameAr: 'بورونغا',
    finalImage: require('../../assets/characters/epic/porunga.png'),
    attack: 13, defense: 12,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'eis_shenron',
    name: 'Eis Shenron',
    nameAr: 'إيس شينرون',
    finalImage: require('../../assets/characters/epic/eis_shenron.png'),
    attack: 15, defense: 11,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'shenron',
    name: 'Shenron',
    nameAr: 'شينرون',
    finalImage: require('../../assets/characters/epic/shenron.png'),
    attack: 15, defense: 11,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'piccolo',
    name: 'Piccolo',
    nameAr: 'بيكولو',
    finalImage: require('../../assets/characters/legendary/piccolo.png'),
    attack: 18, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'syn_shenron',
    name: 'Syn Shenron',
    nameAr: 'سين شينرون',
    finalImage: require('../../assets/characters/legendary/syn_shenron.png'),
    attack: 18, defense: 16,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'trunks',
    name: 'Trunks',
    nameAr: 'ترانكس',
    finalImage: require('../../assets/characters/legendary/trunks.png'),
    attack: 17, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'gohan',
    name: 'Gohan',
    nameAr: 'غوهان',
    finalImage: require('../../assets/characters/legendary/gohan.png'),
    attack: 16, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'cell',
    name: 'Cell',
    nameAr: 'سيل',
    finalImage: require('../../assets/characters/legendary/cell.png'),
    attack: 17, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'frieza',
    name: 'Frieza',
    nameAr: 'فريزا',
    finalImage: require('../../assets/characters/legendary/frieza.png'),
    attack: 17, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'vegeta',
    name: 'Vegeta',
    nameAr: 'فيجيتا',
    finalImage: require('../../assets/characters/legendary/vegeta.png'),
    attack: 17, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'broly',
    name: 'Broly',
    nameAr: 'بروللي',
    finalImage: require('../../assets/characters/legendary/broly.png'),
    attack: 18, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'omega_shenron',
    name: 'Omega Shenron',
    nameAr: 'أوميغا شينرون',
    finalImage: require('../../assets/characters/legendary/omega_shenron.png'),
    attack: 19, defense: 16,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'son_goku',
    name: 'Son Goku',
    nameAr: 'غوكو',
    finalImage: require('../../assets/characters/legendary/son_goku.png'),
    attack: 18, defense: 17,
    race: 'orc', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'hitch_dreyse',
    name: 'Hitch Dreyse',
    nameAr: 'هيتش دريس',
    finalImage: require('../../assets/characters/common/hitch_dreyse.png'),
    attack: 1, defense: 1,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'common', stars: 1,
    animationPreset: 'default',
  },
  {
    id: 'sasha_braus',
    name: 'Sasha Braus',
    nameAr: 'ساشا براوس',
    finalImage: require('../../assets/characters/rare/sasha_braus.png'),
    attack: 8, defense: 6,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'falco_grice',
    name: 'Falco Grice',
    nameAr: 'فالكو غرايس',
    finalImage: require('../../assets/characters/rare/falco_grice.png'),
    attack: 9, defense: 7,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'armin_arlert',
    name: 'Armin Arlert',
    nameAr: 'أرمين أرليرت',
    finalImage: require('../../assets/characters/epic/armin_arlert.png'),
    attack: 13, defense: 11,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'pieck_finger',
    name: 'Pieck Finger',
    nameAr: 'بيك فينغر',
    finalImage: require('../../assets/characters/epic/pieck_finger.png'),
    attack: 11, defense: 12,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'bertholdt_hoover',
    name: 'Bertholdt Hoover',
    nameAr: 'بيرتولدت هوفر',
    finalImage: require('../../assets/characters/epic/bertholdt_hoover.png'),
    attack: 12, defense: 12,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'porco_galliard',
    name: 'Porco Galliard',
    nameAr: 'بوركو غاليارد',
    finalImage: require('../../assets/characters/epic/porco_galliard.png'),
    attack: 14, defense: 11,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'kenny_ackerman',
    name: 'Kenny Ackerman',
    nameAr: 'كيني أكرمان',
    finalImage: require('../../assets/characters/epic/kenny_ackerman.png'),
    attack: 13, defense: 12,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'annie_leonhart',
    name: 'Annie Leonhart',
    nameAr: 'آني ليونهارت',
    finalImage: require('../../assets/characters/epic/annie_leonhart.png'),
    attack: 14, defense: 11,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'mikasa_ackerman',
    name: 'Mikasa Ackerman',
    nameAr: 'ميكاسا أكرمان',
    finalImage: require('../../assets/characters/epic/mikasa_ackerman.png'),
    attack: 15, defense: 14,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'reiner_braun',
    name: 'Reiner Braun',
    nameAr: 'راينر براون',
    finalImage: require('../../assets/characters/legendary/reiner_braun.png'),
    attack: 16, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'zeke_yeager',
    name: 'Zeke Yeager',
    nameAr: 'زيك ييغر',
    finalImage: require('../../assets/characters/legendary/zeke_yeager.png'),
    attack: 16, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'eren_yeager',
    name: 'Eren Yeager',
    nameAr: 'إيرين ييغر',
    finalImage: require('../../assets/characters/legendary/eren_yeager.png'),
    attack: 16, defense: 17,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'levi_ackerman',
    name: 'Levi Ackerman',
    nameAr: 'ليفي أكرمان',
    finalImage: require('../../assets/characters/legendary/levi_ackerman.png'),
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'misa_amane',
    name: 'Misa Amane',
    nameAr: 'ميسا أماني',
    finalImage: require('../../assets/cards/final/human-warrior.png'),  // TODO: missing image
    attack: 1, defense: 2,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'common', stars: 1,
    animationPreset: 'ice',
  },
  {
    id: 'l_lawliet',
    name: 'L (Lawliet)',
    nameAr: 'إل',
    finalImage: require('../../assets/characters/rare/l_lawliet.png'),
    attack: 6, defense: 6,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'ice',
  },
  {
    id: 'light_yagami',
    name: 'Light Yagami',
    nameAr: 'لايت ياغامي',
    finalImage: require('../../assets/characters/rare/light_yagami.png'),
    attack: 8, defense: 6,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'ice',
  },
  {
    id: 'ryuk',
    name: 'Ryuk',
    nameAr: 'ريوك',
    finalImage: require('../../assets/characters/legendary/ryuk.png'),
    attack: 17, defense: 16,
    race: 'demon', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['poison'],
  },
  {
    id: 'inosuke_hashibira',
    name: 'Inosuke Hashibira',
    nameAr: 'إينوسوكي هاشيبيرا',
    finalImage: require('../../assets/characters/epic/inosuke_hashibira.png'),
    attack: 13, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'zenitsu_agatsuma',
    name: 'Zenitsu Agatsuma',
    nameAr: 'زينيتسو أغاتسوما',
    finalImage: require('../../assets/characters/epic/zenitsu_agatsuma.png'),
    attack: 13, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'nezuko_kamado',
    name: 'Nezuko Kamado',
    nameAr: 'نيزوكو كامادو',
    finalImage: require('../../assets/characters/epic/nezuko_kamado.png'),
    attack: 13, defense: 11,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'shinobu_kocho',
    name: 'Shinobu Kocho',
    nameAr: 'شينوبو كوتشو',
    finalImage: require('../../assets/characters/epic/shinobu_kocho.png'),
    attack: 12, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'tanjiro_kamado',
    name: 'Tanjiro Kamado',
    nameAr: 'تانجيرو كامادو',
    finalImage: require('../../assets/characters/epic/tanjiro_kamado.png'),
    attack: 15, defense: 12,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'mitsuri_kanroji',
    name: 'Mitsuri Kanroji',
    nameAr: 'ميتسوري كانروجي',
    finalImage: require('../../assets/characters/epic/mitsuri_kanroji.png'),
    attack: 13, defense: 14,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'gyutaro',
    name: 'Gyutaro',
    nameAr: 'غيوتارو',
    finalImage: require('../../assets/characters/epic/gyutaro.png'),
    attack: 14, defense: 13,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'yamcha',
    name: 'Yamcha',
    nameAr: 'يامتشا',
    finalImage: require('../../assets/characters/rare/yamcha.png'),
    attack: 6, defense: 6,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'fire',
  },
  {
    id: 'tien_shinhan',
    name: 'Tien Shinhan',
    nameAr: 'تيان شينهان',
    finalImage: require('../../assets/characters/rare/tien_shinhan.png'),
    attack: 8, defense: 9,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'fire',
  },
  {
    id: 'krillin',
    name: 'Krillin',
    nameAr: 'كريلين',
    finalImage: require('../../assets/characters/epic/krillin.png'),
    attack: 15, defense: 13,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'nail',
    name: 'Nail',
    nameAr: 'نيل',
    finalImage: require('../../assets/characters/epic/nail.png'),
    attack: 14, defense: 14,
    race: 'elf', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'master_roshi',
    name: 'Master Roshi',
    nameAr: 'الماستر روشي',
    finalImage: require('../../assets/characters/epic/master_roshi.png'),
    attack: 12, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'lord_slug',
    name: 'Lord Slug',
    nameAr: 'اللورد سلوغ',
    finalImage: require('../../assets/characters/epic/lord_slug.png'),
    attack: 14, defense: 11,
    race: 'elf', cardClass: 'knight', element: 'fire',
    tags: ["sword", "shield"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
    cardEffects: ['divine_shield'],
  },
  {
    id: 'rage_shenron',
    name: 'Rage Shenron',
    nameAr: 'راج شينرون',
    finalImage: require('../../assets/characters/epic/rage_shenron.png'),
    attack: 14, defense: 11,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'nuova_shenron',
    name: 'Nuova Shenron',
    nameAr: 'نوفا شينرون',
    finalImage: require('../../assets/characters/epic/nuova_shenron.png'),
    attack: 13, defense: 14,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'porunga',
    name: 'Porunga',
    nameAr: 'بورونغا',
    finalImage: require('../../assets/characters/epic/porunga.png'),
    attack: 13, defense: 12,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'eis_shenron',
    name: 'Eis Shenron',
    nameAr: 'إيس شينرون',
    finalImage: require('../../assets/characters/epic/eis_shenron.png'),
    attack: 15, defense: 11,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'shenron',
    name: 'Shenron',
    nameAr: 'شينرون',
    finalImage: require('../../assets/characters/epic/shenron.png'),
    attack: 15, defense: 11,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'piccolo',
    name: 'Piccolo',
    nameAr: 'بيكولو',
    finalImage: require('../../assets/characters/legendary/piccolo.png'),
    attack: 18, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'syn_shenron',
    name: 'Syn Shenron',
    nameAr: 'سين شينرون',
    finalImage: require('../../assets/characters/legendary/syn_shenron.png'),
    attack: 18, defense: 16,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'trunks',
    name: 'Trunks',
    nameAr: 'ترانكس',
    finalImage: require('../../assets/characters/legendary/trunks.png'),
    attack: 17, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'gohan',
    name: 'Gohan',
    nameAr: 'غوهان',
    finalImage: require('../../assets/characters/legendary/gohan.png'),
    attack: 16, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'cell',
    name: 'Cell',
    nameAr: 'سيل',
    finalImage: require('../../assets/characters/legendary/cell.png'),
    attack: 17, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'frieza',
    name: 'Frieza',
    nameAr: 'فريزا',
    finalImage: require('../../assets/characters/legendary/frieza.png'),
    attack: 17, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'vegeta',
    name: 'Vegeta',
    nameAr: 'فيجيتا',
    finalImage: require('../../assets/characters/legendary/vegeta.png'),
    attack: 17, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'broly',
    name: 'Broly',
    nameAr: 'بروللي',
    finalImage: require('../../assets/characters/legendary/broly.png'),
    attack: 18, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'omega_shenron',
    name: 'Omega Shenron',
    nameAr: 'أوميغا شينرون',
    finalImage: require('../../assets/characters/legendary/omega_shenron.png'),
    attack: 19, defense: 16,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'son_goku',
    name: 'Son Goku',
    nameAr: 'غوكو',
    finalImage: require('../../assets/characters/legendary/son_goku.png'),
    attack: 18, defense: 17,
    race: 'orc', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'hitch_dreyse',
    name: 'Hitch Dreyse',
    nameAr: 'هيتش دريس',
    finalImage: require('../../assets/characters/common/hitch_dreyse.png'),
    attack: 1, defense: 1,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'common', stars: 1,
    animationPreset: 'default',
  },
  {
    id: 'sasha_braus',
    name: 'Sasha Braus',
    nameAr: 'ساشا براوس',
    finalImage: require('../../assets/characters/rare/sasha_braus.png'),
    attack: 8, defense: 6,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'falco_grice',
    name: 'Falco Grice',
    nameAr: 'فالكو غرايس',
    finalImage: require('../../assets/characters/rare/falco_grice.png'),
    attack: 9, defense: 7,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'armin_arlert',
    name: 'Armin Arlert',
    nameAr: 'أرمين أرليرت',
    finalImage: require('../../assets/characters/epic/armin_arlert.png'),
    attack: 13, defense: 11,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'pieck_finger',
    name: 'Pieck Finger',
    nameAr: 'بيك فينغر',
    finalImage: require('../../assets/characters/epic/pieck_finger.png'),
    attack: 11, defense: 12,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'bertholdt_hoover',
    name: 'Bertholdt Hoover',
    nameAr: 'بيرتولدت هوفر',
    finalImage: require('../../assets/characters/epic/bertholdt_hoover.png'),
    attack: 12, defense: 12,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'porco_galliard',
    name: 'Porco Galliard',
    nameAr: 'بوركو غاليارد',
    finalImage: require('../../assets/characters/epic/porco_galliard.png'),
    attack: 14, defense: 11,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'kenny_ackerman',
    name: 'Kenny Ackerman',
    nameAr: 'كيني أكرمان',
    finalImage: require('../../assets/characters/epic/kenny_ackerman.png'),
    attack: 13, defense: 12,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'annie_leonhart',
    name: 'Annie Leonhart',
    nameAr: 'آني ليونهارت',
    finalImage: require('../../assets/characters/epic/annie_leonhart.png'),
    attack: 14, defense: 11,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'mikasa_ackerman',
    name: 'Mikasa Ackerman',
    nameAr: 'ميكاسا أكرمان',
    finalImage: require('../../assets/characters/epic/mikasa_ackerman.png'),
    attack: 15, defense: 14,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'reiner_braun',
    name: 'Reiner Braun',
    nameAr: 'راينر براون',
    finalImage: require('../../assets/characters/legendary/reiner_braun.png'),
    attack: 16, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'zeke_yeager',
    name: 'Zeke Yeager',
    nameAr: 'زيك ييغر',
    finalImage: require('../../assets/characters/legendary/zeke_yeager.png'),
    attack: 16, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'eren_yeager',
    name: 'Eren Yeager',
    nameAr: 'إيرين ييغر',
    finalImage: require('../../assets/characters/legendary/eren_yeager.png'),
    attack: 16, defense: 17,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'levi_ackerman',
    name: 'Levi Ackerman',
    nameAr: 'ليفي أكرمان',
    finalImage: require('../../assets/characters/legendary/levi_ackerman.png'),
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'misa_amane',
    name: 'Misa Amane',
    nameAr: 'ميسا أماني',
    finalImage: require('../../assets/cards/final/human-warrior.png'),  // TODO: missing image
    attack: 1, defense: 2,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'common', stars: 1,
    animationPreset: 'ice',
  },
  {
    id: 'l_lawliet',
    name: 'L (Lawliet)',
    nameAr: 'إل',
    finalImage: require('../../assets/characters/rare/l_lawliet.png'),
    attack: 6, defense: 6,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'ice',
  },
  {
    id: 'light_yagami',
    name: 'Light Yagami',
    nameAr: 'لايت ياغامي',
    finalImage: require('../../assets/characters/rare/light_yagami.png'),
    attack: 8, defense: 6,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'ice',
  },
  {
    id: 'ryuk',
    name: 'Ryuk',
    nameAr: 'ريوك',
    finalImage: require('../../assets/characters/legendary/ryuk.png'),
    attack: 17, defense: 16,
    race: 'demon', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['poison'],
  },
  {
    id: 'inosuke_hashibira',
    name: 'Inosuke Hashibira',
    nameAr: 'إينوسوكي هاشيبيرا',
    finalImage: require('../../assets/characters/epic/inosuke_hashibira.png'),
    attack: 13, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'zenitsu_agatsuma',
    name: 'Zenitsu Agatsuma',
    nameAr: 'زينيتسو أغاتسوما',
    finalImage: require('../../assets/characters/epic/zenitsu_agatsuma.png'),
    attack: 13, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'nezuko_kamado',
    name: 'Nezuko Kamado',
    nameAr: 'نيزوكو كامادو',
    finalImage: require('../../assets/characters/epic/nezuko_kamado.png'),
    attack: 13, defense: 11,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'shinobu_kocho',
    name: 'Shinobu Kocho',
    nameAr: 'شينوبو كوتشو',
    finalImage: require('../../assets/characters/epic/shinobu_kocho.png'),
    attack: 12, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'tanjiro_kamado',
    name: 'Tanjiro Kamado',
    nameAr: 'تانجيرو كامادو',
    finalImage: require('../../assets/characters/epic/tanjiro_kamado.png'),
    attack: 15, defense: 12,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'mitsuri_kanroji',
    name: 'Mitsuri Kanroji',
    nameAr: 'ميتسوري كانروجي',
    finalImage: require('../../assets/characters/epic/mitsuri_kanroji.png'),
    attack: 13, defense: 14,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'gyutaro',
    name: 'Gyutaro',
    nameAr: 'غيوتارو',
    finalImage: require('../../assets/characters/epic/gyutaro.png'),
    attack: 14, defense: 13,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'shoto_todoroki',
    name: 'Shoto Todoroki',
    nameAr: 'شوتو تودوروكي',
    finalImage: require('../../assets/characters/epic/shoto_todoroki.png'),
    attack: 12, defense: 12,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'endeavor',
    name: 'Endeavor',
    nameAr: 'إنديفر',
    finalImage: require('../../assets/characters/epic/endeavor.png'),
    attack: 14, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'katsuki_bakugo',
    name: 'Katsuki Bakugo',
    nameAr: 'كاتسوكي باكوغو',
    finalImage: require('../../assets/characters/epic/katsuki_bakugo.png'),
    attack: 15, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'izuku_midoriya',
    name: 'Izuku Midoriya',
    nameAr: 'إيزوكو ميدوريا',
    finalImage: require('../../assets/characters/epic/izuku_midoriya.png'),
    attack: 14, defense: 15,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'tomura_shigaraki',
    name: 'Tomura Shigaraki',
    nameAr: 'توموروا شيغاراكي',
    finalImage: require('../../assets/characters/epic/tomura_shigaraki.png'),
    attack: 14, defense: 15,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'all_might',
    name: 'All Might',
    nameAr: 'أول مايت',
    finalImage: require('../../assets/characters/legendary/all_might.png'),
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'king',
    name: 'King',
    nameAr: 'كينغ',
    finalImage: require('../../assets/characters/common/king.png'),
    attack: 1, defense: 0,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'common', stars: 1,
    animationPreset: 'lightning',
  },
  {
    id: 'genos',
    name: 'Genos',
    nameAr: 'جينوس',
    finalImage: require('../../assets/characters/epic/genos.png'),
    attack: 12, defense: 11,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'bang',
    name: 'Bang',
    nameAr: 'بانغ',
    finalImage: require('../../assets/characters/epic/bang.png'),
    attack: 15, defense: 12,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'garou',
    name: 'Garou',
    nameAr: 'غارو',
    finalImage: require('../../assets/characters/legendary/garou.png'),
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'tatsumaki',
    name: 'Tatsumaki',
    nameAr: 'تاتسوماكي',
    finalImage: require('../../assets/characters/legendary/tatsumaki.png'),
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'saitama',
    name: 'Saitama',
    nameAr: 'سايتاما',
    finalImage: require('../../assets/characters/legendary/saitama.png'),
    attack: 17, defense: 17,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'the_plain_doll',
    name: 'The Plain Doll',
    nameAr: 'الدمية',
    finalImage: require('../../assets/characters/common/the_plain_doll.png'),
    attack: 3, defense: 0,
    race: 'human', cardClass: 'mage', element: 'water',
    tags: ["magic"],
    rarity: 'common', stars: 1,
    animationPreset: 'default',
  },
  {
    id: 'suspicious_beggar',
    name: 'Suspicious Beggar',
    nameAr: 'المتسول المشبوه',
    finalImage: require('../../assets/characters/rare/suspicious_beggar.png'),
    attack: 9, defense: 7,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'eileen_the_crow',
    name: 'Eileen the Crow',
    nameAr: 'إيلين الغراب',
    finalImage: require('../../assets/characters/epic/eileen_the_crow.png'),
    attack: 12, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'queen_annalise',
    name: 'Queen Annalise',
    nameAr: 'الملكة أناليس',
    finalImage: require('../../assets/characters/epic/queen_annalise.png'),
    attack: 14, defense: 11,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'father_gascoigne',
    name: 'Father Gascoigne',
    nameAr: 'الأب غاسكوين',
    finalImage: require('../../assets/characters/epic/father_gascoigne.png'),
    attack: 14, defense: 11,
    race: 'orc', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'the_hunter',
    name: 'The Hunter',
    nameAr: 'الصياد',
    finalImage: require('../../assets/characters/legendary/the_hunter.png'),
    attack: 18, defense: 16,
    race: 'human', cardClass: 'archer', element: 'ice',
    tags: ["bow", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['charge'],
  },
  {
    id: 'lady_maria',
    name: 'Lady Maria',
    nameAr: 'الليدي ماريا',
    finalImage: require('../../assets/characters/legendary/lady_maria.png'),
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'laurence',
    name: 'Laurence',
    nameAr: 'لورانس',
    finalImage: require('../../assets/characters/legendary/laurence.png'),
    attack: 17, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'gehrman',
    name: 'Gehrman',
    nameAr: 'جيرمان',
    finalImage: require('../../assets/characters/legendary/gehrman.png'),
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'ludwig',
    name: 'Ludwig',
    nameAr: 'لودفيغ',
    finalImage: require('../../assets/characters/legendary/ludwig.png'),
    attack: 17, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'emlyn_white',
    name: 'Emlyn White',
    nameAr: 'إيميلين وايت',
    finalImage: require('../../assets/characters/rare/emlyn_white.png'),
    attack: 8, defense: 7,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'ice',
  },
  {
    id: 'alger_wilson',
    name: 'Alger Wilson',
    nameAr: 'ألغر ويلسون',
    finalImage: require('../../assets/characters/epic/alger_wilson.png'),
    attack: 13, defense: 12,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'audrey_hall',
    name: 'Audrey Hall',
    nameAr: 'أودري هول',
    finalImage: require('../../assets/characters/epic/audrey_hall.png'),
    attack: 15, defense: 12,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'cattleya',
    name: 'Cattleya',
    nameAr: 'كاتليا',
    finalImage: require('../../assets/characters/legendary/cattleya.png'),
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'roselle_gustav',
    name: 'Roselle Gustav',
    nameAr: 'روزيل غوستاف',
    finalImage: require('../../assets/characters/legendary/roselle_gustav.png'),
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'azik_eggers',
    name: 'Azik Eggers',
    nameAr: 'أزيك إيغرز',
    finalImage: require('../../assets/characters/legendary/azik_eggers.png'),
    attack: 16, defense: 16,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['taunt'],
  },
  {
    id: 'klein_moretti',
    name: 'Klein Moretti',
    nameAr: 'كلاين موريتي',
    finalImage: require('../../assets/characters/legendary/klein_moretti.png'),
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'feanor',
    name: 'Feanor',
    nameAr: 'فيانور',
    finalImage: require('../../assets/characters/legendary/feanor.png'),
    attack: 17, defense: 16,
    race: 'elf', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'amon',
    name: 'Amon',
    nameAr: 'أمون',
    finalImage: require('../../assets/characters/legendary/amon.png'),
    attack: 17, defense: 18,
    race: 'orc', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'rin_okumura',
    name: 'Rin Okumura',
    nameAr: 'رين أوكومورا',
    finalImage: require('../../assets/characters/epic/rin_okumura.png'),
    attack: 15, defense: 11,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'amaimon',
    name: 'Amaimon',
    nameAr: 'عمايمون',
    finalImage: require('../../assets/characters/epic/amaimon.png'),
    attack: 13, defense: 14,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'satan',
    name: 'Satan',
    nameAr: 'ساتان',
    finalImage: require('../../assets/characters/legendary/satan.png'),
    attack: 19, defense: 16,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'lilith',
    name: 'Lilith',
    nameAr: 'ليليث',
    finalImage: require('../../assets/characters/legendary/lilith.png'),
    attack: 16, defense: 17,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'diablo',
    name: 'Diablo',
    nameAr: 'ديابلو',
    finalImage: require('../../assets/characters/legendary/diablo.png'),
    attack: 19, defense: 16,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'lucifer',
    name: 'Lucifer',
    nameAr: 'لوسيفر',
    finalImage: require('../../assets/characters/legendary/lucifer.png'),
    attack: 18, defense: 16,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'power',
    name: 'Power',
    nameAr: 'باور',
    finalImage: require('../../assets/characters/epic/power.png'),
    attack: 12, defense: 12,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'denji',
    name: 'Denji',
    nameAr: 'دينجي',
    finalImage: require('../../assets/characters/epic/denji.png'),
    attack: 15, defense: 11,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'makima',
    name: 'Makima',
    nameAr: 'ماكيما',
    finalImage: require('../../assets/characters/legendary/makima.png'),
    attack: 17, defense: 16,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'ram',
    name: 'Ram',
    nameAr: 'رام',
    finalImage: require('../../assets/characters/rare/ram.png'),
    attack: 8, defense: 8,
    race: 'elf', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'ice',
  },
  {
    id: 'rem',
    name: 'Rem',
    nameAr: 'ريم',
    finalImage: require('../../assets/characters/epic/rem.png'),
    attack: 14, defense: 15,
    race: 'orc', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'emilia',
    name: 'Emilia',
    nameAr: 'إيميليا',
    finalImage: require('../../assets/characters/epic/emilia.png'),
    attack: 11, defense: 11,
    race: 'elf', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'puck',
    name: 'Puck',
    nameAr: 'باك',
    finalImage: require('../../assets/characters/epic/puck.png'),
    attack: 12, defense: 12,
    race: 'elf', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'petelgeuse',
    name: 'Petelgeuse',
    nameAr: 'بيتلغيوز',
    finalImage: require('../../assets/characters/epic/petelgeuse.png'),
    attack: 13, defense: 11,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'beatrice',
    name: 'Beatrice',
    nameAr: 'بياتريس',
    finalImage: require('../../assets/characters/epic/beatrice.png'),
    attack: 14, defense: 11,
    race: 'elf', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'echidna',
    name: 'Echidna',
    nameAr: 'إيكيدنا',
    finalImage: require('../../assets/characters/epic/echidna.png'),
    attack: 15, defense: 14,
    race: 'elf', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'roswaal',
    name: 'Roswaal',
    nameAr: 'روزوال',
    finalImage: require('../../assets/characters/epic/roswaal.png'),
    attack: 15, defense: 12,
    race: 'elf', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'satella',
    name: 'Satella',
    nameAr: 'ساتيلا',
    finalImage: require('../../assets/characters/legendary/satella.png'),
    attack: 19, defense: 16,
    race: 'elf', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'zelda',
    name: 'Zelda',
    nameAr: 'زيلدا',
    finalImage: require('../../assets/characters/epic/zelda.png'),
    attack: 14, defense: 13,
    race: 'elf', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'impa',
    name: 'Impa',
    nameAr: 'إمبا',
    finalImage: require('../../assets/characters/epic/impa.png'),
    attack: 13, defense: 12,
    race: 'elf', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'midna',
    name: 'Midna',
    nameAr: 'ميدنا',
    finalImage: require('../../assets/characters/epic/midna.png'),
    attack: 15, defense: 11,
    race: 'elf', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'link',
    name: 'Link',
    nameAr: 'لينك',
    finalImage: require('../../assets/characters/epic/link.png'),
    attack: 15, defense: 11,
    race: 'elf', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'ganondorf',
    name: 'Ganondorf',
    nameAr: 'غانوندورف',
    finalImage: require('../../assets/characters/legendary/ganondorf.png'),
    attack: 16, defense: 17,
    race: 'elf', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'silica',
    name: 'Silica',
    nameAr: 'سيليكا',
    finalImage: require('../../assets/characters/rare/silica.png'),
    attack: 9, defense: 9,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'yui',
    name: 'Yui',
    nameAr: 'يوي',
    finalImage: require('../../assets/characters/rare/yui.png'),
    attack: 7, defense: 6,
    race: 'human', cardClass: 'mage', element: 'earth',
    tags: ["magic"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'titania_asuna',
    name: 'Titania (Asuna)',
    nameAr: 'تيتانيا (أسونا)',
    finalImage: require('../../assets/characters/epic/titania_asuna.png'),
    attack: 13, defense: 11,
    race: 'elf', cardClass: 'berserker', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
    cardEffects: ['charge'],
  },
  {
    id: 'eugeo',
    name: 'Eugeo',
    nameAr: 'يوجيو',
    finalImage: require('../../assets/characters/epic/eugeo.png'),
    attack: 13, defense: 12,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'heathcliff_kayaba',
    name: 'Heathcliff (Kayaba)',
    nameAr: 'هيثكليف (كايابا)',
    finalImage: require('../../assets/characters/epic/heathcliff_kayaba.png'),
    attack: 13, defense: 13,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'alice_zuberg',
    name: 'Alice Zuberg',
    nameAr: 'أليس زيوبيرغ',
    finalImage: require('../../assets/characters/epic/alice_zuberg.png'),
    attack: 13, defense: 13,
    race: 'elf', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'rundelhaus',
    name: 'Rundelhaus',
    nameAr: 'روندلهاوس',
    finalImage: require('../../assets/characters/rare/rundelhaus.png'),
    attack: 8, defense: 8,
    race: 'elf', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'regan',
    name: 'Regan',
    nameAr: 'ريغان',
    finalImage: require('../../assets/characters/epic/regan.png'),
    attack: 13, defense: 11,
    race: 'elf', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'nyanta',
    name: 'Nyanta',
    nameAr: 'نيانتا',
    finalImage: require('../../assets/characters/epic/nyanta.png'),
    attack: 11, defense: 12,
    race: 'elf', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'akatsuki',
    name: 'Akatsuki',
    nameAr: 'أكاتسوكي',
    finalImage: require('../../assets/characters/epic/akatsuki.png'),
    attack: 13, defense: 12,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'odahviing',
    name: 'Odahviing',
    nameAr: 'أوداهفيينغ',
    finalImage: require('../../assets/characters/epic/odahviing.png'),
    attack: 13, defense: 12,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'durnehviir',
    name: 'Durnehviir',
    nameAr: 'دورنيهفير',
    finalImage: require('../../assets/characters/epic/durnehviir.png'),
    attack: 15, defense: 11,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'paarthurnax',
    name: 'Paarthurnax',
    nameAr: 'بارثورناكس',
    finalImage: require('../../assets/characters/legendary/paarthurnax.png'),
    attack: 16, defense: 17,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'alduin',
    name: 'Alduin',
    nameAr: 'ألدوين',
    finalImage: require('../../assets/characters/legendary/alduin.png'),
    attack: 17, defense: 16,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'happy',
    name: 'Happy',
    nameAr: 'هابي',
    finalImage: require('../../assets/characters/common/happy.png'),
    attack: 4, defense: 2,
    race: 'orc', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'common', stars: 2,
    animationPreset: 'fire',
  },
  {
    id: 'elfman_strauss',
    name: 'Elfman Strauss',
    nameAr: 'إيلفمان شتراوس',
    finalImage: require('../../assets/characters/epic/elfman_strauss.png'),
    attack: 12, defense: 11,
    race: 'elf', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'torafuzar',
    name: 'Torafuzar',
    nameAr: 'تورافوزار',
    finalImage: require('../../assets/characters/epic/torafuzar.png'),
    attack: 12, defense: 11,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'motherglare',
    name: 'Motherglare',
    nameAr: 'موذرغلير',
    finalImage: require('../../assets/characters/epic/motherglare.png'),
    attack: 14, defense: 11,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'zirconis',
    name: 'Zirconis',
    nameAr: 'زيركونيس',
    finalImage: require('../../assets/characters/epic/zirconis.png'),
    attack: 15, defense: 11,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'atlas_flame',
    name: 'Atlas Flame',
    nameAr: 'أطلس فليم',
    finalImage: require('../../assets/characters/epic/atlas_flame.png'),
    attack: 15, defense: 11,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'mirajane_strauss',
    name: 'Mirajane Strauss',
    nameAr: 'ميراجين شتراوس',
    finalImage: require('../../assets/characters/epic/mirajane_strauss.png'),
    attack: 13, defense: 14,
    race: 'elf', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'weisslogia',
    name: 'Weisslogia',
    nameAr: 'وايسلوجيا',
    finalImage: require('../../assets/characters/epic/weisslogia.png'),
    attack: 14, defense: 14,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'skiadrum',
    name: 'Skiadrum',
    nameAr: 'سكيادروم',
    finalImage: require('../../assets/characters/epic/skiadrum.png'),
    attack: 15, defense: 11,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'grandeeney',
    name: 'Grandeeney',
    nameAr: 'غرانديني',
    finalImage: require('../../assets/characters/epic/grandeeney.png'),
    attack: 14, defense: 15,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'igneel',
    name: 'Igneel',
    nameAr: 'إيغنيل',
    finalImage: require('../../assets/characters/legendary/igneel.png'),
    attack: 16, defense: 17,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'mavis_vermillion',
    name: 'Mavis Vermillion',
    nameAr: 'ماڤيس فيرميليون',
    finalImage: require('../../assets/characters/legendary/mavis_vermillion.png'),
    attack: 17, defense: 16,
    race: 'elf', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'acnologia',
    name: 'Acnologia',
    nameAr: 'أكنولوجيا',
    finalImage: require('../../assets/characters/legendary/acnologia.png'),
    attack: 16, defense: 16,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'zeref_dragneel',
    name: 'Zeref Dragneel',
    nameAr: 'زيريف دراغنيل',
    finalImage: require('../../assets/characters/legendary/zeref_dragneel.png'),
    attack: 16, defense: 17,
    race: 'elf', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'brachydios',
    name: 'Brachydios',
    nameAr: 'براكيديوس',
    finalImage: require('../../assets/characters/epic/brachydios.png'),
    attack: 12, defense: 12,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'zinogre',
    name: 'Zinogre',
    nameAr: 'زينوغري',
    finalImage: require('../../assets/characters/epic/zinogre.png'),
    attack: 15, defense: 11,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'nergigante',
    name: 'Nergigante',
    nameAr: 'نيرغيغانتي',
    finalImage: require('../../assets/characters/epic/nergigante.png'),
    attack: 15, defense: 12,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'fatalis',
    name: 'Fatalis',
    nameAr: 'فاتاليس',
    finalImage: require('../../assets/characters/legendary/fatalis.png'),
    attack: 18, defense: 16,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'hector',
    name: 'Hector',
    nameAr: 'هيكتور',
    finalImage: require('../../assets/characters/epic/hector.png'),
    attack: 14, defense: 11,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'isaac',
    name: 'Isaac',
    nameAr: 'إسحاق',
    finalImage: require('../../assets/characters/epic/isaac.png'),
    attack: 15, defense: 11,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'carmilla',
    name: 'Carmilla',
    nameAr: 'كارميلا',
    finalImage: require('../../assets/characters/epic/carmilla.png'),
    attack: 14, defense: 11,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'alucard',
    name: 'Alucard',
    nameAr: 'ألوكارد',
    finalImage: require('../../assets/characters/legendary/alucard.png'),
    attack: 18, defense: 16,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['taunt'],
  },
  {
    id: 'death',
    name: 'Death',
    nameAr: 'الموت',
    finalImage: require('../../assets/characters/legendary/death.png'),
    attack: 18, defense: 16,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['taunt'],
  },
  {
    id: 'dracula',
    name: 'Dracula',
    nameAr: 'دراكولا',
    finalImage: require('../../assets/characters/legendary/dracula.png'),
    attack: 18, defense: 16,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['taunt'],
  },
  {
    id: 'sif_the_wolf',
    name: 'Sif the Wolf',
    nameAr: 'سيف الذئب',
    finalImage: require('../../assets/characters/epic/sif_the_wolf.png'),
    attack: 14, defense: 12,
    race: 'orc', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'smough',
    name: 'Smough',
    nameAr: 'سماو',
    finalImage: require('../../assets/characters/epic/smough.png'),
    attack: 15, defense: 11,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'ornstein',
    name: 'Ornstein',
    nameAr: 'أورنشتاين',
    finalImage: require('../../assets/characters/epic/ornstein.png'),
    attack: 15, defense: 12,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'gwyn',
    name: 'Gwyn',
    nameAr: 'غوين',
    finalImage: require('../../assets/characters/legendary/gwyn.png'),
    attack: 17, defense: 16,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['taunt'],
  },
  {
    id: 'artorias',
    name: 'Artorias',
    nameAr: 'أرتورياس',
    finalImage: require('../../assets/characters/legendary/artorias.png'),
    attack: 16, defense: 17,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['taunt'],
  },
  {
    id: 'lich_general',
    name: 'Lich (General)',
    nameAr: 'ليتش العام',
    finalImage: require('../../assets/characters/epic/lich_general.png'),
    attack: 15, defense: 13,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'pandoras_actor',
    name: 'Pandora\'s Actor',
    nameAr: 'ممثل باندورا',
    finalImage: require('../../assets/characters/epic/pandoras_actor.png'),
    attack: 15, defense: 11,
    race: 'human', cardClass: 'mage', element: 'ice',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'aura_bella_fiora',
    name: 'Aura Bella Fiora',
    nameAr: 'أورا بيلا فيورا',
    finalImage: require('../../assets/characters/epic/aura_bella_fiora.png'),
    attack: 14, defense: 13,
    race: 'elf', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'mare_bello_fiore',
    name: 'Mare Bello Fiore',
    nameAr: 'ماري بيلو فيوري',
    finalImage: require('../../assets/characters/epic/mare_bello_fiore.png'),
    attack: 14, defense: 11,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'albedo',
    name: 'Albedo',
    nameAr: 'ألبيدو',
    finalImage: require('../../assets/characters/epic/albedo.png'),
    attack: 15, defense: 12,
    race: 'orc', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'cocytus',
    name: 'Cocytus',
    nameAr: 'كوسيتوس',
    finalImage: require('../../assets/characters/epic/cocytus.png'),
    attack: 13, defense: 12,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'shalltear',
    name: 'Shalltear',
    nameAr: 'شالتير',
    finalImage: require('../../assets/characters/epic/shalltear.png'),
    attack: 14, defense: 15,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'ainz_ooal_gown',
    name: 'Ainz Ooal Gown',
    nameAr: 'آينز أوال غاون',
    finalImage: require('../../assets/characters/legendary/ainz_ooal_gown.png'),
    attack: 17, defense: 16,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['taunt'],
  },
  {
    id: 'caretaker',
    name: 'Caretaker',
    nameAr: 'الحارس',
    finalImage: require('../../assets/characters/epic/caretaker.png'),
    attack: 12, defense: 12,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'regis',
    name: 'Regis',
    nameAr: 'ريجيس',
    finalImage: require('../../assets/characters/epic/regis.png'),
    attack: 15, defense: 12,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'dettlaff',
    name: 'Dettlaff',
    nameAr: 'ديتلاف',
    finalImage: require('../../assets/characters/epic/dettlaff.png'),
    attack: 15, defense: 11,
    race: 'orc', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'gaunter_o_dimm',
    name: 'Gaunter O Dimm',
    nameAr: 'غونتر أو ديم',
    finalImage: require('../../assets/characters/legendary/gaunter_o_dimm.png'),
    attack: 17, defense: 16,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['taunt'],
  },
  {
    id: 'floki',
    name: 'Floki',
    nameAr: 'فلوكي',
    finalImage: require('../../assets/characters/rare/floki.png'),
    attack: 9, defense: 8,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'ice',
  },
  {
    id: 'askeladd',
    name: 'Askeladd',
    nameAr: 'أسكيلاد',
    finalImage: require('../../assets/characters/epic/askeladd.png'),
    attack: 13, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'thorfinn',
    name: 'Thorfinn',
    nameAr: 'ثورفين',
    finalImage: require('../../assets/characters/epic/thorfinn.png'),
    attack: 12, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'thorkell',
    name: 'Thorkell',
    nameAr: 'ثوركيل',
    finalImage: require('../../assets/characters/epic/thorkell.png'),
    attack: 13, defense: 14,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'yuta_okkotsu',
    name: 'Yuta Okkotsu',
    nameAr: 'يوتا أوكوتسو',
    finalImage: require('../../assets/characters/epic/yuta_okkotsu.png'),
    attack: 15, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'nia_teppelin',
    name: 'Nia Teppelin',
    nameAr: 'نيا تيبلين',
    finalImage: require('../../assets/characters/rare/nia_teppelin.png'),
    attack: 9, defense: 8,
    race: 'human', cardClass: 'mage', element: 'earth',
    tags: ["magic"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'kamina',
    name: 'Kamina',
    nameAr: 'كامينا',
    finalImage: require('../../assets/characters/epic/kamina.png'),
    attack: 12, defense: 11,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'viral',
    name: 'Viral',
    nameAr: 'فايرال',
    finalImage: require('../../assets/characters/epic/viral.png'),
    attack: 15, defense: 12,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'lordgenome',
    name: 'Lordgenome',
    nameAr: 'لورد غينوم',
    finalImage: require('../../assets/characters/epic/lordgenome.png'),
    attack: 14, defense: 13,
    race: 'human', cardClass: 'knight', element: 'lightning',
    tags: ["sword", "shield"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
    cardEffects: ['divine_shield'],
  },
  {
    id: 'shinji_ikari',
    name: 'Shinji Ikari',
    nameAr: 'شينجي إيكاري',
    finalImage: require('../../assets/characters/epic/shinji_ikari.png'),
    attack: 14, defense: 13,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'asuka_langley',
    name: 'Asuka Langley',
    nameAr: 'أسوكا لانغلي',
    finalImage: require('../../assets/characters/epic/asuka_langley.png'),
    attack: 13, defense: 11,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'rei_ayanami',
    name: 'Rei Ayanami',
    nameAr: 'ري أيانامي',
    finalImage: require('../../assets/characters/epic/rei_ayanami.png'),
    attack: 13, defense: 14,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'kaworu_nagisa',
    name: 'Kaworu Nagisa',
    nameAr: 'كاورو ناغيسا',
    finalImage: require('../../assets/characters/epic/kaworu_nagisa.png'),
    attack: 14, defense: 13,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'unit_01',
    name: 'Unit-01',
    nameAr: 'الوحدة 01',
    finalImage: require('../../assets/characters/legendary/unit_01.png'),
    attack: 16, defense: 16,
    race: 'human', cardClass: 'mage', element: 'ice',
    tags: ["magic", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'dr_cossack',
    name: 'Dr. Cossack',
    nameAr: 'د. كوساك',
    finalImage: require('../../assets/characters/rare/dr_cossack.png'),
    attack: 6, defense: 6,
    race: 'human', cardClass: 'mage', element: 'earth',
    tags: ["magic"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'mega_man',
    name: 'Mega Man',
    nameAr: 'ميغا مان',
    finalImage: require('../../assets/characters/epic/mega_man.png'),
    attack: 13, defense: 12,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'bass',
    name: 'Bass',
    nameAr: 'باس',
    finalImage: require('../../assets/characters/epic/bass.png'),
    attack: 15, defense: 11,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'zero',
    name: 'Zero',
    nameAr: 'زيرو',
    finalImage: require('../../assets/characters/epic/zero.png'),
    attack: 15, defense: 12,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'sigma',
    name: 'Sigma',
    nameAr: 'سيغما',
    finalImage: require('../../assets/characters/epic/sigma.png'),
    attack: 14, defense: 14,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'zodd',
    name: 'Zodd',
    nameAr: 'زود',
    finalImage: require('../../assets/characters/epic/zodd.png'),
    attack: 15, defense: 12,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'griffith_dragon',
    name: 'Griffith Dragon',
    nameAr: 'غريفث التنين',
    finalImage: require('../../assets/characters/legendary/griffith_dragon.png'),
    attack: 16, defense: 16,
    race: 'dragon', cardClass: 'warrior', element: 'earth',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'guts',
    name: 'Guts',
    nameAr: 'غاتس',
    finalImage: require('../../assets/characters/legendary/guts.png'),
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'griffith',
    name: 'Griffith',
    nameAr: 'غريفث',
    finalImage: require('../../assets/characters/legendary/griffith.png'),
    attack: 16, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'clare',
    name: 'Clare',
    nameAr: 'كلير',
    finalImage: require('../../assets/characters/epic/clare.png'),
    attack: 13, defense: 11,
    race: 'orc', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'teresa',
    name: 'Teresa',
    nameAr: 'تيريزا',
    finalImage: require('../../assets/characters/legendary/teresa.png'),
    attack: 17, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'neferpitou',
    name: 'Neferpitou',
    nameAr: 'نيفيربيتو',
    finalImage: require('../../assets/characters/epic/neferpitou.png'),
    attack: 15, defense: 11,
    race: 'orc', cardClass: 'warrior', element: 'wind',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'colossal_titan',
    name: 'Colossal Titan',
    nameAr: 'التيتان العملاق',
    finalImage: require('../../assets/characters/epic/colossal_titan.png'),
    attack: 15, defense: 12,
    race: 'orc', cardClass: 'berserker', element: 'earth',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
    cardEffects: ['charge'],
  },
  {
    id: 'mineta',
    name: 'Mineta',
    nameAr: 'مينيتا',
    finalImage: require('../../assets/characters/common/mineta.png'),
    attack: 3, defense: 2,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'common', stars: 2,
    animationPreset: 'lightning',
  },
];
