import { Card, Element, ElementAdvantage, Effect, ELEMENT_ADVANTAGES, ELEMENT_WEAKNESSES, ELEMENT_MULTIPLIER } from './types';

// Batch 3/6 — Cards 93 to 138
// Universes: Demon Slayer, HxH, Bleach, FMA, JJK, TG, MHA

export const CARDS_BATCH_3: Card[] = [
  {
    id: 'tengen_uzui',
    name: 'Tengen Uzui',
    nameAr: 'تينغين أوزوي',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'kyojuro_rengoku',
    name: 'Kyojuro Rengoku',
    nameAr: 'كوجورو رينغوكو',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'muichiro_tokito',
    name: 'Muichiro Tokito',
    nameAr: 'مويتشيرو توكيتو',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'giyu_tomioka',
    name: 'Giyu Tomioka',
    nameAr: 'غيو توميوكا',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 16, defense: 17,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'doma',
    name: 'Doma',
    nameAr: 'دوما',
    finalImage: require('../../assets/cards/final/demon-warrior.png'), // TODO: missing image
    attack: 16, defense: 16,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'kokushibo',
    name: 'Kokushibo',
    nameAr: 'كوكوشيبو',
    finalImage: require('../../assets/cards/final/demon-warrior.png'), // TODO: missing image
    attack: 17, defense: 16,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'akaza',
    name: 'Akaza',
    nameAr: 'أكازا',
    finalImage: require('../../assets/cards/final/demon-warrior.png'), // TODO: missing image
    attack: 18, defense: 16,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'muzan_kibutsuji',
    name: 'Muzan Kibutsuji',
    nameAr: 'موزان كيبوتسوجي',
    finalImage: require('../../assets/cards/final/demon-warrior.png'), // TODO: missing image
    attack: 18, defense: 16,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'leorio',
    name: 'Leorio',
    nameAr: 'ليوريو',
    finalImage: require('../../assets/cards/final/human-warrior.png'),
    attack: 3, defense: 2,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword"],
    rarity: 'common', stars: 2,
    animationPreset: 'default',
  },
  {
    id: 'kite',
    name: 'Kite',
    nameAr: 'كايت',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 12, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'kurapika',
    name: 'Kurapika',
    nameAr: 'كورابيكا',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 15, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'illumi_zoldyck',
    name: 'Illumi Zoldyck',
    nameAr: 'إيلومي زولديك',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 14, defense: 15,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'gon_freecss',
    name: 'Gon Freecss',
    nameAr: 'غون فريكس',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 16, defense: 17,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'killua_zoldyck',
    name: 'Killua Zoldyck',
    nameAr: 'كيلوا زولديك',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'chrollo_lucilfer',
    name: 'Chrollo Lucilfer',
    nameAr: 'كرولو لوسيلفر',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 16, defense: 17,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'hisoka_morow',
    name: 'Hisoka Morow',
    nameAr: 'هيسوكا مورو',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'isaac_netero',
    name: 'Isaac Netero',
    nameAr: 'إسحاق نيتيرو',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'meruem',
    name: 'Meruem',
    nameAr: 'ميريوم',
    finalImage: require('../../assets/cards/final/orc-warrior.png'), // TODO: missing image
    attack: 17, defense: 18,
    race: 'orc', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'nemu_kurotsuchi',
    name: 'Nemu Kurotsuchi',
    nameAr: 'نيمو كوروتسوتشي',
    finalImage: require('../../assets/cards/final/human-mage.png'), // TODO: missing image
    attack: 13, defense: 11,
    race: 'human', cardClass: 'mage', element: 'ice',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'cirucci_sanderwicci',
    name: 'Cirucci Sanderwicci',
    nameAr: 'سيروتشي',
    finalImage: require('../../assets/cards/final/human-mage.png'), // TODO: missing image
    attack: 13, defense: 11,
    race: 'human', cardClass: 'mage', element: 'ice',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'rukia_kuchiki',
    name: 'Rukia Kuchiki',
    nameAr: 'روكيا كوتشيكي',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 13, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'kenpachi_zaraki',
    name: 'Kenpachi Zaraki',
    nameAr: 'كينباتشي زاراكي',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'byakuya_kuchiki',
    name: 'Byakuya Kuchiki',
    nameAr: 'بياكويا كوتشيكي',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'ichigo_kurosaki',
    name: 'Ichigo Kurosaki',
    nameAr: 'إيتشيغو كوروساكي',
    finalImage: require('../../assets/cards/final/demon-warrior.png'), // TODO: missing image
    attack: 18, defense: 16,
    race: 'demon', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['poison'],
  },
  {
    id: 'sosuke_aizen',
    name: 'Sosuke Aizen',
    nameAr: 'سوسيكي أيزن',
    finalImage: require('../../assets/cards/final/demon-warrior.png'), // TODO: missing image
    attack: 18, defense: 17,
    race: 'demon', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['poison'],
  },
  {
    id: 'barry_the_chopper',
    name: 'Barry the Chopper',
    nameAr: 'باري الجزار',
    finalImage: require('../../assets/cards/final/human-mage.png'), // TODO: missing image
    attack: 8, defense: 9,
    race: 'human', cardClass: 'mage', element: 'fire',
    tags: ["magic"],
    rarity: 'rare', stars: 3,
    animationPreset: 'fire',
  },
  {
    id: 'martel',
    name: 'Martel',
    nameAr: 'مارتيل',
    finalImage: require('../../assets/cards/final/human-mage.png'), // TODO: missing image
    attack: 8, defense: 8,
    race: 'human', cardClass: 'mage', element: 'fire',
    tags: ["magic"],
    rarity: 'rare', stars: 3,
    animationPreset: 'fire',
  },
  {
    id: 'envy',
    name: 'Envy',
    nameAr: 'الحسد',
    finalImage: require('../../assets/cards/final/demon-warrior.png'), // TODO: missing image
    attack: 12, defense: 11,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'olivier_armstrong',
    name: 'Olivier Armstrong',
    nameAr: 'أوليفيه أرمسترونغ',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 12, defense: 13,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'greed',
    name: 'Greed',
    nameAr: 'الجشع',
    finalImage: require('../../assets/cards/final/demon-warrior.png'), // TODO: missing image
    attack: 13, defense: 11,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'roy_mustang',
    name: 'Roy Mustang',
    nameAr: 'روي موستانغ',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 14, defense: 13,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'alphonse_elric',
    name: 'Alphonse Elric',
    nameAr: 'ألفونس إلريك',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 15, defense: 12,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'edward_elric',
    name: 'Edward Elric',
    nameAr: 'إدوارد إلريك',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 15, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'pride',
    name: 'Pride',
    nameAr: 'الكبرياء',
    finalImage: require('../../assets/cards/final/demon-warrior.png'), // TODO: missing image
    attack: 18, defense: 16,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'megumi_fushiguro',
    name: 'Megumi Fushiguro',
    nameAr: 'ميغومي فوشيغورو',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 12, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'nanami_kento',
    name: 'Nanami Kento',
    nameAr: 'ناناميكينتو',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 13, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'aoi_todo',
    name: 'Aoi Todo',
    nameAr: 'أوي تودو',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 12, defense: 13,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'suguru_geto',
    name: 'Suguru Geto',
    nameAr: 'سوغورو غيتو',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 14, defense: 13,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'yuji_itadori',
    name: 'Yuji Itadori',
    nameAr: 'يوجي إيتادوري',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 14, defense: 13,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'satoru_gojo',
    name: 'Satoru Gojo',
    nameAr: 'ساتورو غوجو',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 18, defense: 17,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'ryomen_sukuna',
    name: 'Ryomen Sukuna',
    nameAr: 'ريومن سوكونا',
    finalImage: require('../../assets/cards/final/demon-warrior.png'), // TODO: missing image
    attack: 17, defense: 16,
    race: 'demon', cardClass: 'warrior', element: 'lightning',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
    cardEffects: ['poison'],
  },
  {
    id: 'touka_kirishima',
    name: 'Touka Kirishima',
    nameAr: 'توكا كيريشيما',
    finalImage: require('../../assets/cards/final/demon-warrior.png'), // TODO: missing image
    attack: 15, defense: 13,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'eto_yoshimura',
    name: 'Eto Yoshimura',
    nameAr: 'إيتو يوشيمورا',
    finalImage: require('../../assets/cards/final/demon-warrior.png'), // TODO: missing image
    attack: 14, defense: 14,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'kishou_arima',
    name: 'Kishou Arima',
    nameAr: 'كيشو أريما',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'ken_kaneki',
    name: 'Ken Kaneki',
    nameAr: 'كين كانيكي',
    finalImage: require('../../assets/cards/final/demon-warrior.png'), // TODO: missing image
    attack: 16, defense: 16,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'hawks',
    name: 'Hawks',
    nameAr: 'هوكس',
    finalImage: require('../../assets/cards/final/human-warrior.png'), // TODO: missing image
    attack: 13, defense: 12,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
];
