import { Card, Element, ElementAdvantage, Effect, ELEMENT_ADVANTAGES, ELEMENT_WEAKNESSES, ELEMENT_MULTIPLIER } from './types';

// Batch 5/6 — Cards 185 to 230
// Universes: Re:Zero, The Legend of Zelda, Sword Art Online, Log Horizon, The Elder Scrolls, Fairy Tail, Monster Hunter, Castlevania

export const CARDS_BATCH_5: Card[] = [
  {
    id: 'echidna',
    name: 'Echidna',
    nameAr: 'إيكيدنا',
    attack: 15, defense: 14,
    race: 'elf', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'roswaal',
    name: 'Roswaal',
    nameAr: 'روزوال',
    attack: 15, defense: 12,
    race: 'elf', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'satella',
    name: 'Satella',
    nameAr: 'ساتيلا',
    attack: 19, defense: 16,
    race: 'elf', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'zelda',
    name: 'Zelda',
    nameAr: 'زيلدا',
    attack: 14, defense: 13,
    race: 'elf', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'impa',
    name: 'Impa',
    nameAr: 'إمبا',
    attack: 13, defense: 12,
    race: 'elf', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'midna',
    name: 'Midna',
    nameAr: 'ميدنا',
    attack: 15, defense: 11,
    race: 'elf', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'link',
    name: 'Link',
    nameAr: 'لينك',
    attack: 15, defense: 11,
    race: 'elf', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'ganondorf',
    name: 'Ganondorf',
    nameAr: 'غانوندورف',
    attack: 16, defense: 17,
    race: 'elf', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'silica',
    name: 'Silica',
    nameAr: 'سيليكا',
    attack: 9, defense: 9,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'yui',
    name: 'Yui',
    nameAr: 'يوي',
    attack: 7, defense: 6,
    race: 'human', cardClass: 'mage', element: 'earth',
    tags: ["magic"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'titania_asuna',
    name: 'Titania (Asuna)',
    nameAr: 'تيتانيا (أسونا)',
    attack: 13, defense: 11,
    race: 'elf', cardClass: 'berserker', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
    cardEffects: ['charge'],
  },
  {
    id: 'eugeo',
    name: 'Eugeo',
    nameAr: 'يوجيو',
    attack: 13, defense: 12,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'heathcliff_kayaba',
    name: 'Heathcliff (Kayaba)',
    nameAr: 'هيثكليف (كايابا)',
    attack: 13, defense: 13,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'alice_zuberg',
    name: 'Alice Zuberg',
    nameAr: 'أليس زيوبيرغ',
    attack: 13, defense: 13,
    race: 'elf', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'rundelhaus',
    name: 'Rundelhaus',
    nameAr: 'روندلهاوس',
    attack: 8, defense: 8,
    race: 'elf', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'regan',
    name: 'Regan',
    nameAr: 'ريغان',
    attack: 13, defense: 11,
    race: 'elf', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'nyanta',
    name: 'Nyanta',
    nameAr: 'نيانتا',
    attack: 11, defense: 12,
    race: 'elf', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'akatsuki',
    name: 'Akatsuki',
    nameAr: 'أكاتسوكي',
    attack: 13, defense: 12,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'odahviing',
    name: 'Odahviing',
    nameAr: 'أوداهفيينغ',
    attack: 13, defense: 12,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'durnehviir',
    name: 'Durnehviir',
    nameAr: 'دورنيهفير',
    attack: 15, defense: 11,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'paarthurnax',
    name: 'Paarthurnax',
    nameAr: 'بارثورناكس',
    attack: 16, defense: 17,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'alduin',
    name: 'Alduin',
    nameAr: 'ألدوين',
    attack: 17, defense: 16,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'happy',
    name: 'Happy',
    nameAr: 'هابي',
    finalImage: require('../../assets/cards/final/orc-warrior.png'),
    attack: 4, defense: 2,
    race: 'orc', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'common', stars: 2,
    animationPreset: 'fire',
  },
  {
    id: 'elfman_strauss',
    name: 'Elfman Strauss',
    nameAr: 'إيلفمان شتراوس',
    attack: 12, defense: 11,
    race: 'elf', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'torafuzar',
    name: 'Torafuzar',
    nameAr: 'تورافوزار',
    attack: 12, defense: 11,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'motherglare',
    name: 'Motherglare',
    nameAr: 'موذرغلير',
    attack: 14, defense: 11,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'zirconis',
    name: 'Zirconis',
    nameAr: 'زيركونيس',
    attack: 15, defense: 11,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'atlas_flame',
    name: 'Atlas Flame',
    nameAr: 'أطلس فليم',
    attack: 15, defense: 11,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'mirajane_strauss',
    name: 'Mirajane Strauss',
    nameAr: 'ميراجين شتراوس',
    attack: 13, defense: 14,
    race: 'elf', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'weisslogia',
    name: 'Weisslogia',
    nameAr: 'وايسلوجيا',
    attack: 14, defense: 14,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'skiadrum',
    name: 'Skiadrum',
    nameAr: 'سكيادروم',
    attack: 15, defense: 11,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'grandeeney',
    name: 'Grandeeney',
    nameAr: 'غرانديني',
    attack: 14, defense: 15,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'igneel',
    name: 'Igneel',
    nameAr: 'إيغنيل',
    attack: 16, defense: 17,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'mavis_vermillion',
    name: 'Mavis Vermillion',
    nameAr: 'ماڤيس فيرميليون',
    attack: 17, defense: 16,
    race: 'elf', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'acnologia',
    name: 'Acnologia',
    nameAr: 'أكنولوجيا',
    attack: 16, defense: 16,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'zeref_dragneel',
    name: 'Zeref Dragneel',
    nameAr: 'زيريف دراغنيل',
    attack: 16, defense: 17,
    race: 'elf', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'brachydios',
    name: 'Brachydios',
    nameAr: 'براكيديوس',
    attack: 12, defense: 12,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'zinogre',
    name: 'Zinogre',
    nameAr: 'زينوغري',
    attack: 15, defense: 11,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'nergigante',
    name: 'Nergigante',
    nameAr: 'نيرغيغانتي',
    attack: 15, defense: 12,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'fatalis',
    name: 'Fatalis',
    nameAr: 'فاتاليس',
    attack: 18, defense: 16,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'hector',
    name: 'Hector',
    nameAr: 'هيكتور',
    attack: 14, defense: 11,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'isaac',
    name: 'Isaac',
    nameAr: 'إسحاق',
    attack: 15, defense: 11,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'carmilla',
    name: 'Carmilla',
    nameAr: 'كارميلا',
    attack: 14, defense: 11,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'alucard',
    name: 'Alucard',
    nameAr: 'ألوكارد',
    attack: 18, defense: 16,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['taunt'],
  },
  {
    id: 'death',
    name: 'Death',
    nameAr: 'الموت',
    attack: 18, defense: 16,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['taunt'],
  },
  {
    id: 'dracula',
    name: 'Dracula',
    nameAr: 'دراكولا',
    attack: 18, defense: 16,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['taunt'],
  },
];